/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.projeto.view;

import br.programa.dao.DadosPedidosDAO;
import br.programa.dao.NotasFiscaisDAO;
import br.programa.model.DadosPedidos;
import br.programa.model.DadosRecebimento;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author samuc
 */
public class FrmAuditoriaNf extends javax.swing.JFrame {
    
    
    
    DadosPedidos objpes = new DadosPedidos();
    
    public void setTextoDoLabelAnterior(String texto) {
        lblusuario.setText(texto); // substitua "meuLabelNaNovaTela" pelo nome do seu label na FrmInPedidos
    }
    
    /**
     * Creates new form FrmRecebimentos
     */
    
    public void limparTabela(JTable tabela) {
    DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
    modelo.setRowCount(0);
}
    
    public FrmAuditoriaNf() {
        initComponents();
        
        // Define a imagem da barra superior
        setIconImage(new ImageIcon(getClass().getResource("/imagens/get2.png")).getImage());

        // Define o título
        setTitle("Auditoria");
    }
            FrmReceberNF1 frmReceberNF1 = new FrmReceberNF1();
            FrmRetornarRecebimentoNF frmRetornarRecebimentoNF = new FrmRetornarRecebimentoNF();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TblPedidosRec = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        TxtNumOfPesq = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        CbCentrodeCusto = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        lblusuario = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TblPedidosRec.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TblPedidosRec.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nº NF", "Nº OF", "VALOR TOTAL", "CENTRO DE CUSTO", "DATA 1", "DATA 2", "DATA 3", "STATUS", "OBS", "null", "null"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TblPedidosRec.setRowHeight(40);
        TblPedidosRec.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(TblPedidosRec);
        if (TblPedidosRec.getColumnModel().getColumnCount() > 0) {
            TblPedidosRec.getColumnModel().getColumn(0).setMinWidth(25);
            TblPedidosRec.getColumnModel().getColumn(0).setPreferredWidth(25);
            TblPedidosRec.getColumnModel().getColumn(0).setMaxWidth(25);
            TblPedidosRec.getColumnModel().getColumn(1).setMinWidth(80);
            TblPedidosRec.getColumnModel().getColumn(1).setPreferredWidth(80);
            TblPedidosRec.getColumnModel().getColumn(1).setMaxWidth(80);
            TblPedidosRec.getColumnModel().getColumn(2).setMinWidth(80);
            TblPedidosRec.getColumnModel().getColumn(2).setPreferredWidth(80);
            TblPedidosRec.getColumnModel().getColumn(2).setMaxWidth(80);
            TblPedidosRec.getColumnModel().getColumn(3).setMinWidth(80);
            TblPedidosRec.getColumnModel().getColumn(3).setPreferredWidth(80);
            TblPedidosRec.getColumnModel().getColumn(3).setMaxWidth(80);
            TblPedidosRec.getColumnModel().getColumn(4).setPreferredWidth(80);
            TblPedidosRec.getColumnModel().getColumn(5).setMinWidth(0);
            TblPedidosRec.getColumnModel().getColumn(5).setPreferredWidth(0);
            TblPedidosRec.getColumnModel().getColumn(5).setMaxWidth(0);
            TblPedidosRec.getColumnModel().getColumn(6).setMinWidth(0);
            TblPedidosRec.getColumnModel().getColumn(6).setPreferredWidth(0);
            TblPedidosRec.getColumnModel().getColumn(6).setMaxWidth(0);
            TblPedidosRec.getColumnModel().getColumn(7).setMinWidth(0);
            TblPedidosRec.getColumnModel().getColumn(7).setPreferredWidth(0);
            TblPedidosRec.getColumnModel().getColumn(7).setMaxWidth(0);
            TblPedidosRec.getColumnModel().getColumn(9).setMinWidth(0);
            TblPedidosRec.getColumnModel().getColumn(9).setPreferredWidth(0);
            TblPedidosRec.getColumnModel().getColumn(9).setMaxWidth(0);
            TblPedidosRec.getColumnModel().getColumn(10).setMinWidth(0);
            TblPedidosRec.getColumnModel().getColumn(10).setPreferredWidth(0);
            TblPedidosRec.getColumnModel().getColumn(10).setMaxWidth(0);
            TblPedidosRec.getColumnModel().getColumn(11).setMinWidth(0);
            TblPedidosRec.getColumnModel().getColumn(11).setPreferredWidth(0);
            TblPedidosRec.getColumnModel().getColumn(11).setMaxWidth(0);
        }

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/setas-direitas.png"))); // NOI18N
        jButton3.setText("IR PARA AUDITORIA");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/search.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Nº Nota Fiscal");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/LOGO MENOR.png"))); // NOI18N

        CbCentrodeCusto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AREA PROGRAMATICA 3.1", "AREA PROGRAMATICA 5.2", "AREA PROGRAMATICA 2.2", "HOSPITAL MUNICIPAL PIEDADE", "HOSPITAL MUNICIPAL DR GILSON CANTARINO", "HOSPITAL MUNICIPAL FRANCISCO DA SILVA TELLES", "HOSPITAL MUNICIPAL ALBERT SCHWEITZER" }));
        CbCentrodeCusto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbCentrodeCustoActionPerformed(evt);
            }
        });

        jLabel3.setText("Centro de Custo");

        lblusuario.setBackground(new java.awt.Color(51, 255, 102));
        lblusuario.setForeground(new java.awt.Color(0, 204, 51));
        lblusuario.setText("Teste");

        jLabel9.setText("Usuário:");

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/setas-direitas.png"))); // NOI18N
        jButton4.setText("RETORNAR RECEBIMENTO");
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtNumOfPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CbCentrodeCusto, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2))
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(161, 161, 161)
                                .addComponent(jLabel1))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 893, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TxtNumOfPesq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CbCentrodeCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(jButton4))
                        .addGap(6, 6, 6))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(lblusuario))
                        .addComponent(jLabel1)))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(28, 170, 158));
        jPanel4.setForeground(new java.awt.Color(0, 0, 51));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("I - FATURAMENTO - PESQUISA DE ENTREGA");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        String id = "%" + TxtNumOfPesq.getText() + "%";
        String status = "AGUARDANDO AUDITORIA";
        String ccusto = CbCentrodeCusto.getSelectedItem().toString();
        
        NotasFiscaisDAO dao = new NotasFiscaisDAO();
        List<DadosRecebimento> lista = dao.buscaNotaFiscalStatusAuditoria(id,status,ccusto);
        DefaultTableModel dados = (DefaultTableModel) TblPedidosRec.getModel();
        dados.setNumRows(0);

        for (DadosRecebimento d : lista) {
            dados.addRow(new Object[]{
                d.getId(),
                d.getNumnf(),
                d.getNumeroOF(),
                d.getValor_total(),
                d.getProjeto(),
                d.getData_rec(),
                d.getData_emissao(),
                d.getData_emv(),
                d.getStatus(),
                d.getObs1(),
                d.getFornecedor(),
                d.getCnpj(),
                
            });
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        String textoDoLabel1 = lblusuario.getText();


  int row = TblPedidosRec.getSelectedRow();
    
    // Obter os valores das células da linha selecionada
    String valor1 = TblPedidosRec.getValueAt(row, 0).toString(); // Supondo que a primeira coluna contenha o valor1
    String valor2 = TblPedidosRec.getValueAt(row, 1).toString(); // Supondo que a segunda coluna contenha o valor2
    String valor3 = TblPedidosRec.getValueAt(row, 2).toString(); // Supondo que a segunda coluna contenha o valor2
    String valor4 = TblPedidosRec.getValueAt(row, 3).toString(); // Supondo que a segunda coluna contenha o valor2
    String valor5 = TblPedidosRec.getValueAt(row, 4).toString(); // Supondo que a segunda coluna contenha o valor2
    String valor6 = TblPedidosRec.getValueAt(row, 5).toString(); // Supondo que a segunda coluna contenha o valor2
    String valor7 = TblPedidosRec.getValueAt(row, 6).toString(); // Supondo que a segunda coluna contenha o valor2
    String valor8 = TblPedidosRec.getValueAt(row, 6).toString(); // Supondo que a segunda coluna contenha o valor2
    String valor9 = TblPedidosRec.getValueAt(row, 9).toString(); // Supondo que a segunda coluna contenha o valor2
    String valor10 = TblPedidosRec.getValueAt(row, 10).toString(); // Supondo que a segunda coluna contenha o valor2
    String valor11 = TblPedidosRec.getValueAt(row, 11).toString(); // Supondo que a segunda coluna contenha o valor2
    

            SimpleDateFormat formatoMysql = new SimpleDateFormat("yyyy-MM-dd");

        try {
            // Converte a data do MySQL para um objeto Date
            Date data = formatoMysql.parse(valor6);
            Date data2 = formatoMysql.parse(valor7);
            Date data3 = formatoMysql.parse(valor8);

            // Cria um objeto SimpleDateFormat com o formato brasileiro
            SimpleDateFormat formatoBrasileiro = new SimpleDateFormat("dd/MM/yyyy");

            // Converte a data para o formato brasileiro
            String dataFormatada = formatoBrasileiro.format(data);
            String dataFormatada2 = formatoBrasileiro.format(data2);
            String dataFormatada3 = formatoBrasileiro.format(data3);

            // Define a data formatada no JTextField
            FrmReceberNF1.TxtDataReceb.setText(dataFormatada);
            FrmReceberNF1.TxtDataEnvio.setText(dataFormatada2);
            FrmReceberNF1.TxtDataEmissao.setText(dataFormatada3);
        } catch (java.text.ParseException e) {
            // Trate a exceção caso a data do MySQL não possa ser convertida para uma data
            e.printStackTrace();
        }
    
    
            // Setar os valores nos JTextFields do formulário FrmReceberNF1
            FrmReceberNF1.TxtId.setText(valor1);
            FrmReceberNF1.TxtNumNF.setText(valor2);
            FrmReceberNF1.TxtNumOf.setText(valor3);
            FrmReceberNF1.TxtValorNf.setText(valor4);
            FrmReceberNF1.TxtProjeto.setText(valor5);
            FrmReceberNF1.jTextPane1.setText(valor9);
            FrmReceberNF1.TxtFornecedor.setText(valor10);
            FrmReceberNF1.TxtCnpj.setText(valor11);

    
//    String nome = "%" + FrmReceberNF1.TxtNumOf.getText() + "%";
    String nome = "%" + valor3 + "%";

    
    DadosPedidosDAO dao = new DadosPedidosDAO();
        List<DadosPedidos> lista = dao.listerItens(nome);
        DefaultTableModel dados = (DefaultTableModel) FrmReceberNF1.TblListarItens.getModel();
        dados.setNumRows(0);

        for (DadosPedidos d : lista) {
            dados.addRow(new Object[]{
                d.getId(),
                d.getCod(),
                d.getItem(),
                d.getUnMedida(),
                d.getP_unit(),
                d.getQtd(),
                d.getFornecedor(),
                d.getCnpjFornecedor()
    }); 
        }
        
        frmReceberNF1.setUsuario(textoDoLabel1);
        
        limparTabela(TblPedidosRec);
        
        frmReceberNF1.setVisible(true);
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        String textoDoLabel1 = lblusuario.getText();


  int row = TblPedidosRec.getSelectedRow();
    
    // Obter os valores das células da linha selecionada
    String valor1 = TblPedidosRec.getValueAt(row, 0).toString(); // Supondo que a primeira coluna contenha o valor1
    String valor2 = TblPedidosRec.getValueAt(row, 1).toString(); // Supondo que a segunda coluna contenha o valor2
    String valor3 = TblPedidosRec.getValueAt(row, 2).toString(); // Supondo que a segunda coluna contenha o valor2
    String valor4 = TblPedidosRec.getValueAt(row, 3).toString(); // Supondo que a segunda coluna contenha o valor2
    String valor5 = TblPedidosRec.getValueAt(row, 4).toString(); // Supondo que a segunda coluna contenha o valor2
    String valor6 = TblPedidosRec.getValueAt(row, 5).toString(); // Supondo que a segunda coluna contenha o valor2
    String valor7 = TblPedidosRec.getValueAt(row, 6).toString(); // Supondo que a segunda coluna contenha o valor2
    String valor8 = TblPedidosRec.getValueAt(row, 6).toString(); // Supondo que a segunda coluna contenha o valor2
    String valor9 = TblPedidosRec.getValueAt(row, 9).toString(); // Supondo que a segunda coluna contenha o valor2
    

            SimpleDateFormat formatoMysql = new SimpleDateFormat("yyyy-MM-dd");

        try {
            // Converte a data do MySQL para um objeto Date
            Date data = formatoMysql.parse(valor6);
            Date data2 = formatoMysql.parse(valor7);
            Date data3 = formatoMysql.parse(valor8);

            // Cria um objeto SimpleDateFormat com o formato brasileiro
            SimpleDateFormat formatoBrasileiro = new SimpleDateFormat("dd/MM/yyyy");

            // Converte a data para o formato brasileiro
            String dataFormatada = formatoBrasileiro.format(data);
            String dataFormatada2 = formatoBrasileiro.format(data2);
            String dataFormatada3 = formatoBrasileiro.format(data3);

            // Define a data formatada no JTextField
            FrmRetornarRecebimentoNF.TxtDataReceb.setText(dataFormatada);
            FrmRetornarRecebimentoNF.TxtDataEnvio.setText(dataFormatada2);
            FrmRetornarRecebimentoNF.TxtDataEmissao.setText(dataFormatada3);
        } catch (java.text.ParseException e) {
            // Trate a exceção caso a data do MySQL não possa ser convertida para uma data
            e.printStackTrace();
        }
    
    
            // Setar os valores nos JTextFields do formulário FrmReceberNF1
            FrmRetornarRecebimentoNF.TxtId.setText(valor1);
            FrmRetornarRecebimentoNF.TxtNumNF.setText(valor2);
            FrmRetornarRecebimentoNF.TxtNumOf.setText(valor3);
            FrmRetornarRecebimentoNF.TxtValorNf.setText(valor4);
            FrmRetornarRecebimentoNF.TxtProjeto.setText(valor5);
//            FrmRetornarRecebimentoNF.jTextPane1.setText(valor9);

    
//    String nome = "%" + FrmReceberNF1.TxtNumOf.getText() + "%";
    String nome = valor3;
    
    DadosPedidosDAO dao = new DadosPedidosDAO();
        List<DadosPedidos> lista = dao.listerItens(nome);
        DefaultTableModel dados1 = (DefaultTableModel) FrmRetornarRecebimentoNF.TblListarItens.getModel();
        dados1.setNumRows(0);

        for (DadosPedidos d : lista) {
            dados1.addRow(new Object[]{
                d.getId(),
                d.getCod(),
                d.getItem(),
                d.getUnMedida(),
                d.getP_unit(),
                d.getPrevisão(),
                d.getUltimaentrada(),
    }); 
        }
        
        frmRetornarRecebimentoNF.setUsuario(textoDoLabel1);
        
        limparTabela(TblPedidosRec);
        
        frmRetornarRecebimentoNF.setVisible(true);
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void CbCentrodeCustoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbCentrodeCustoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbCentrodeCustoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAuditoriaNf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAuditoriaNf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAuditoriaNf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAuditoriaNf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAuditoriaNf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbCentrodeCusto;
    private javax.swing.JTable TblPedidosRec;
    private javax.swing.JTextField TxtNumOfPesq;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblusuario;
    // End of variables declaration//GEN-END:variables
}
