/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.projeto.view;

import br.programa.model.CurrencyRenderer;
import br.programa.dao.DadosPedidosDAO;
import br.programa.dao.InPedidosDAO;
import br.programa.model.DadosPedidos;
import br.programa.model.InPedidos;
import br.programa.model.Utilitarios;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.DefaultCellEditor;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author samuc
 */
public class FrmDadosPedidosOK extends javax.swing.JFrame {
    
    public void setUsuario(String usuario) {
        // Faça o que quiser com o texto da label lblusuario na FrmDadosPedidosOk
        // Por exemplo, exiba o texto em um label na FrmDadosPedidosOk
        lblusuario.setText(usuario); // substitua "lblUsuarioNaNovaTela" pelo nome do seu label na FrmDadosPedidosOk
    }
    
    private FrmPesquisarFornecedor frmPesquisarFornecedor;
    
    CurrencyRenderer currencyRenderer = new CurrencyRenderer();
    
    JTable tblPedidosOk;
    NumberFormat currencyFormat = new DecimalFormat("R$0.00"); // Define o formato de moeda

   DefaultTableModel FrmDadosPedidosOKModel; 
   
       @Override
    public void dispose() {
        super.dispose(); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
        
        DefaultTableModel model = (DefaultTableModel) TblPedidosOk.getModel();
        int rows = model.getRowCount();
        for (int i = rows - 1; i >= 0; i--) {
            model.removeRow(i);
        
    }}


    /**
     * Creates new form FrmDadosPedido
     * 
     */
//    private FrmPesquisarFornecedor FrmPesquisarFornecedor;
    
    public FrmDadosPedidosOK() {
        initComponents();
        tableHeaders();

               
        this.frmPesquisarFornecedor = new FrmPesquisarFornecedor();
    }
    
    public void tableHeaders(){
        
        FrmDadosPedidosOKModel =(DefaultTableModel) TblPedidosOk.getModel();
        
    }
    
     public void atualizarTexto(String texto) {
        JOptionPane.showMessageDialog(null,texto);
        TxtFornecedorDados.setText(texto);
        
    }
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        TxtCnpj = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TxtNumOf = new javax.swing.JTextField();
        TxtIdFonecedor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        TxtFornecedorDados = new javax.swing.JTextField();
        CbComprador = new javax.swing.JComboBox<>();
        cbDigOf = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        TxtCentroDeCusto = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TxtDataEnvioOf = new com.toedter.calendar.JDateChooser();
        TxtTipo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblPedidosOk = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblusuario = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(39, 95, 118));
        jPanel3.setForeground(new java.awt.Color(0, 0, 51));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ll - INSERIR DADOS DO PEDIDOS - ATUALIZAR DADOS DA OF");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TxtCnpj.setEditable(false);
        jPanel2.add(TxtCnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 230, -1));

        jLabel5.setText("FORNECEDOR");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel9.setText("CNPJ");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, -1));

        jLabel6.setText("Modalidade Aquisição");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, -1, -1));

        jLabel10.setText("ID");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 33, -1));

        TxtNumOf.setEditable(false);
        jPanel2.add(TxtNumOf, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 80, -1));

        TxtIdFonecedor.setEditable(false);
        TxtIdFonecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtIdFonecedorActionPerformed(evt);
            }
        });
        jPanel2.add(TxtIdFonecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 33, -1));

        jLabel2.setText("Número OF");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/search.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 72, 38, 30));

        jLabel4.setText("Data Envio OF");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, -1));

        TxtFornecedorDados.setEditable(false);
        TxtFornecedorDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFornecedorDadosActionPerformed(evt);
            }
        });
        jPanel2.add(TxtFornecedorDados, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 243, -1));

        CbComprador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não se Aplica - Registro de Preço", "Aliceseilane Lopes", "Samuel Silva", "João Castilho", "Vanessa Moreira", "Gustavo Lemos" }));
        jPanel2.add(CbComprador, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, 177, -1));

        cbDigOf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ".01", ".02", ".03", ".04", ".05", ".06", ".07", ".08", ".09", ".10", ".11", ".12", ".13", ".14", ".15", ".16", ".17", ".18", ".19", ".20", ".21", ".22", ".23", ".24", ".25", ".26", ".27", ".28", ".29", ".30" }));
        cbDigOf.setPreferredSize(new java.awt.Dimension(47, 22));
        cbDigOf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDigOfActionPerformed(evt);
            }
        });
        jPanel2.add(cbDigOf, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, 20));

        jLabel12.setText("Final");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        jLabel13.setText("Comprador");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 9, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Compra Direta", "Registro de Preço" }));
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(845, 31, 120, -1));

        TxtCentroDeCusto.setEditable(false);
        TxtCentroDeCusto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCentroDeCustoActionPerformed(evt);
            }
        });
        jPanel2.add(TxtCentroDeCusto, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 30, 200, -1));

        jLabel11.setText("Centro de Custo");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 10, 100, -1));
        jPanel2.add(TxtDataEnvioOf, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 149, -1));

        TxtTipo.setEditable(false);
        TxtTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTipoActionPerformed(evt);
            }
        });
        jPanel2.add(TxtTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 90, -1));

        jLabel14.setText("Tipo Pedido");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 90, -1));

        TblPedidosOk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CENTRO CUSTO", "Nº PEDIDO", "COD VIVA RIO", "ITEM", "UM", "PREÇO UNIT", "QTD", "STATUS", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TblPedidosOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblPedidosOkMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TblPedidosOk);
        if (TblPedidosOk.getColumnModel().getColumnCount() > 0) {
            TblPedidosOk.getColumnModel().getColumn(0).setMinWidth(35);
            TblPedidosOk.getColumnModel().getColumn(0).setPreferredWidth(35);
            TblPedidosOk.getColumnModel().getColumn(0).setMaxWidth(35);
            TblPedidosOk.getColumnModel().getColumn(1).setMinWidth(0);
            TblPedidosOk.getColumnModel().getColumn(1).setPreferredWidth(0);
            TblPedidosOk.getColumnModel().getColumn(1).setMaxWidth(0);
            TblPedidosOk.getColumnModel().getColumn(2).setMinWidth(0);
            TblPedidosOk.getColumnModel().getColumn(2).setPreferredWidth(0);
            TblPedidosOk.getColumnModel().getColumn(2).setMaxWidth(0);
            TblPedidosOk.getColumnModel().getColumn(3).setMinWidth(100);
            TblPedidosOk.getColumnModel().getColumn(3).setPreferredWidth(100);
            TblPedidosOk.getColumnModel().getColumn(3).setMaxWidth(100);
            TblPedidosOk.getColumnModel().getColumn(4).setMinWidth(340);
            TblPedidosOk.getColumnModel().getColumn(4).setPreferredWidth(340);
            TblPedidosOk.getColumnModel().getColumn(4).setMaxWidth(340);
            TblPedidosOk.getColumnModel().getColumn(5).setMinWidth(80);
            TblPedidosOk.getColumnModel().getColumn(5).setPreferredWidth(80);
            TblPedidosOk.getColumnModel().getColumn(5).setMaxWidth(80);
            TblPedidosOk.getColumnModel().getColumn(6).setMinWidth(90);
            TblPedidosOk.getColumnModel().getColumn(6).setPreferredWidth(90);
            TblPedidosOk.getColumnModel().getColumn(6).setMaxWidth(90);
            TblPedidosOk.getColumnModel().getColumn(7).setMinWidth(70);
            TblPedidosOk.getColumnModel().getColumn(7).setPreferredWidth(70);
            TblPedidosOk.getColumnModel().getColumn(7).setMaxWidth(70);
            TblPedidosOk.getColumnModel().getColumn(9).setMinWidth(100);
            TblPedidosOk.getColumnModel().getColumn(9).setPreferredWidth(100);
            TblPedidosOk.getColumnModel().getColumn(9).setMaxWidth(100);
        }
        TblPedidosOk.getColumnModel().getColumn(6).setCellRenderer(new CurrencyRenderer());
        // Crie um NumberFormat que permite a entrada de números decimais com vírgula
        NumberFormat format = NumberFormat.getNumberInstance();
        format.setGroupingUsed(false);
        format.setMinimumFractionDigits(2);
        format.setMaximumFractionDigits(2);
        DecimalFormat decimalFormat = (DecimalFormat) format;
        decimalFormat.setParseBigDecimal(true);

        // Crie um NumberFormatter com o NumberFormat configurado
        NumberFormatter formatter = new NumberFormatter(decimalFormat);

        // Crie um JFormattedTextField com o NumberFormatter configurado
        JFormattedTextField textField = new JFormattedTextField(formatter);

        // Defina a coluna 6 (índice 5) do JTable para usar o DefaultCellEditor com o JFormattedTextField
        TblPedidosOk.getColumnModel().getColumn(6).setCellEditor(new DefaultCellEditor(textField));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/LOGO MENOR.png"))); // NOI18N

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/checked (1).png"))); // NOI18N
        jButton2.setText("Cadastrar Dados");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Usuário:");

        lblusuario.setBackground(new java.awt.Color(51, 255, 102));
        lblusuario.setForeground(new java.awt.Color(0, 204, 51));
        lblusuario.setText("Teste");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(369, 369, 369)
                        .addComponent(jLabel8))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel8)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(lblusuario)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      
         Calendar calendar = Calendar.getInstance();
        Date currentDate = calendar.getTime();
        Date selectedDate = TxtDataEnvioOf.getDate();
        
                if (selectedDate.compareTo(currentDate) > 0) {
            JOptionPane.showMessageDialog(null,"Por favor, verificar a data selecionada, pois está em em modo futuro!");
            return;
        } else { 
        
        if(TxtIdFonecedor.getText().isEmpty()){
            
            JOptionPane.showMessageDialog(null, "Por favor, selecionar o fornecedor", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        else{

        DadosPedidos obj3 = new DadosPedidos();
        String value1 = TxtNumOf.getText();
        Object value2 = cbDigOf.getSelectedItem();
        String resultado = value1+value2;
          
        
        DadosPedidosDAO dao2 = new DadosPedidosDAO();
        
         if (dao2.verificarNomeDuplicado(resultado)) {
        // Se o nome já estiver cadastrado, exibe uma mensagem de erro e não cadastra
        JOptionPane.showMessageDialog(null, "Já existe um pedido cadastrado com esse final, por favor verificar número do pedido", "Erro", JOptionPane.ERROR_MESSAGE);
    } else {
         DadosPedidos obj = new DadosPedidos();

            for (int i =0; i <TblPedidosOk.getRowCount();i++){

                    
                Date data = TxtDataEnvioOf.getDate();
                SimpleDateFormat formatador = new SimpleDateFormat("yyyy-MM-dd");
                String dataformatada = formatador.format(data);   
                    
                    
                 obj.setPedidoId(TxtNumOf.getText());
                 obj.setNumeroOF(TxtNumOf.getText()+cbDigOf.getSelectedItem());
                 obj.setData_Envio_OF(dataformatada);
                 obj.setTipo(TxtTipo.getText());
                 obj.setFornecedor(TxtFornecedorDados.getText());
                 obj.setCnpjFornecedor(TxtCnpj.getText());
                 obj.setIdForn(TxtIdFonecedor.getText());
                 obj.setCc(TxtCentroDeCusto.getText());
                 obj.setComprador(CbComprador.getSelectedItem().toString());
                 obj.setP_unit(TblPedidosOk.getValueAt(i, 6).toString());
                 obj.setCod(TblPedidosOk.getValueAt(i, 3).toString());
                 obj.setItem(TblPedidosOk.getValueAt(i, 4).toString());
                 obj.setUnMedida(TblPedidosOk.getValueAt(i, 5).toString());
                 obj.setQtd(TblPedidosOk.getValueAt(i, 7).toString());
                 obj.setStatus(TblPedidosOk.getValueAt(i, 8).toString());
                 
                 obj.setId(Integer.parseInt(TblPedidosOk.getValueAt(i, 0).toString()));
                 obj.setPrevisão(TblPedidosOk.getValueAt(i, 7).toString());
                 obj.setTotal("0");


                 System.out.println(TblPedidosOk.getValueAt(i,7));


                
                
                 obj.setStatus("AGUARDANDO RECEBIMENTO");
              
                                
                 DadosPedidosDAO dao = new DadosPedidosDAO();
                 dao.editar5(obj); 
                 dao.cadastrarOF(obj); 
            }
            
            InPedidos obj1 = new InPedidos();
            obj1.setNum_pedido_sica(TxtNumOf.getText());
            obj1.setStatus_pedido("RECEBIMENTO INICIADO");
            
            InPedidosDAO dao1 = new InPedidosDAO();
            dao1.alterarStatusPedido(obj1);
            
            
            new Utilitarios().LimpaTela(jPanel2);

            this.dispose();
        }
        }

    }//GEN-LAST:event_jButton2ActionPerformed
    }
        public boolean IsSelected(int row, int column, JTable TblPedidos){
         
         return TblPedidos.getValueAt(row, column) !=null;
         
     }
    private void TblPedidosOkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblPedidosOkMouseClicked
        // TODO add your handling code here:  
       
    }//GEN-LAST:event_TblPedidosOkMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
//            this.FrmPesquisarFornecedor.set this.TxtFornecedorDados.setText(String.valueOf(this.FrmPesquisarFornecedor.getForn()));Visible(true);
            this.frmPesquisarFornecedor.setVisible(true);
            

//           
           
    }//GEN-LAST:event_jButton3ActionPerformed

    private void TxtFornecedorDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFornecedorDadosActionPerformed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_TxtFornecedorDadosActionPerformed

    private void cbDigOfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDigOfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDigOfActionPerformed

    private void TxtIdFonecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIdFonecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtIdFonecedorActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
                
                 TxtNumOf.setText(TblPedidosOk.getValueAt(0,2).toString());
                 TxtCentroDeCusto.setText(TblPedidosOk.getValueAt(0,1).toString());
                 TxtTipo.setText(TblPedidosOk.getValueAt(0,9).toString());
    }//GEN-LAST:event_formWindowActivated

    private void TxtCentroDeCustoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCentroDeCustoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCentroDeCustoActionPerformed

    private void TxtTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDadosPedidosOK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDadosPedidosOK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDadosPedidosOK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDadosPedidosOK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDadosPedidosOK().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbComprador;
    private javax.swing.JTable TblPedidosOk;
    private javax.swing.JTextField TxtCentroDeCusto;
    public static javax.swing.JTextField TxtCnpj;
    private com.toedter.calendar.JDateChooser TxtDataEnvioOf;
    public static javax.swing.JTextField TxtFornecedorDados;
    public static javax.swing.JTextField TxtIdFonecedor;
    private javax.swing.JTextField TxtNumOf;
    private javax.swing.JTextField TxtTipo;
    private javax.swing.JComboBox<String> cbDigOf;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblusuario;
    // End of variables declaration//GEN-END:variables


  
}

