/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.projeto.view;

import br.programa.dao.DadosPedidosDAO;
import br.programa.model.DadosPedidos;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author samuc
 */
public class FrmDadosPedidoNovo extends javax.swing.JFrame {
    
    DadosPedidos objpes = new DadosPedidos();
    
    public String usuariologado;
    
    
    public void setTextoDoLabelAnterior(String texto) {
        lblusuario.setText(texto); // substitua "meuLabelNaNovaTela" pelo nome do seu label na FrmInPedidos
    }
    
public void limparTabela(JTable tabela) {
    DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
    modelo.setRowCount(0);
}
    /**
     * Creates new form FrmRecebimentos
     */
    public FrmDadosPedidoNovo() {
        initComponents();
        
        // Define a imagem da barra superior
        setIconImage(new ImageIcon(getClass().getResource("/imagens/get2.png")).getImage());

        // Define o título
        setTitle("Dados do pedido - Pesquisar");
        
        
    }
            FrmDadosPedidosOK FrmDadosPedidosOK = new FrmDadosPedidosOK();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TblDaddosPedidoNovo = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        TxtNumOfPesqNovo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblusuario = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxtFiltrar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TblDaddosPedidoNovo1 = new javax.swing.JTable();
        TxtFiltrar1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        TblDaddosPedidoNovo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CENTRO DE CUSTO", "Nº OF", "CÓDIGO", "ITEM", "UN", "QTD. PEDIDO", "STATUS", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TblDaddosPedidoNovo.setRowHeight(20);
        TblDaddosPedidoNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblDaddosPedidoNovoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TblDaddosPedidoNovo);
        if (TblDaddosPedidoNovo.getColumnModel().getColumnCount() > 0) {
            TblDaddosPedidoNovo.getColumnModel().getColumn(0).setMinWidth(25);
            TblDaddosPedidoNovo.getColumnModel().getColumn(0).setPreferredWidth(25);
            TblDaddosPedidoNovo.getColumnModel().getColumn(0).setMaxWidth(25);
            TblDaddosPedidoNovo.getColumnModel().getColumn(1).setMinWidth(150);
            TblDaddosPedidoNovo.getColumnModel().getColumn(1).setPreferredWidth(150);
            TblDaddosPedidoNovo.getColumnModel().getColumn(1).setMaxWidth(150);
            TblDaddosPedidoNovo.getColumnModel().getColumn(2).setMinWidth(80);
            TblDaddosPedidoNovo.getColumnModel().getColumn(2).setPreferredWidth(80);
            TblDaddosPedidoNovo.getColumnModel().getColumn(2).setMaxWidth(80);
            TblDaddosPedidoNovo.getColumnModel().getColumn(3).setMinWidth(80);
            TblDaddosPedidoNovo.getColumnModel().getColumn(3).setPreferredWidth(80);
            TblDaddosPedidoNovo.getColumnModel().getColumn(3).setMaxWidth(80);
            TblDaddosPedidoNovo.getColumnModel().getColumn(4).setPreferredWidth(80);
            TblDaddosPedidoNovo.getColumnModel().getColumn(5).setPreferredWidth(40);
            TblDaddosPedidoNovo.getColumnModel().getColumn(5).setMaxWidth(40);
            TblDaddosPedidoNovo.getColumnModel().getColumn(6).setMinWidth(50);
            TblDaddosPedidoNovo.getColumnModel().getColumn(6).setPreferredWidth(50);
            TblDaddosPedidoNovo.getColumnModel().getColumn(6).setMaxWidth(50);
            TblDaddosPedidoNovo.getColumnModel().getColumn(7).setPreferredWidth(20);
            TblDaddosPedidoNovo.getColumnModel().getColumn(8).setMinWidth(100);
            TblDaddosPedidoNovo.getColumnModel().getColumn(8).setPreferredWidth(100);
            TblDaddosPedidoNovo.getColumnModel().getColumn(8).setMaxWidth(100);
        }

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/setas-direitas.png"))); // NOI18N
        jButton3.setText("INSERIR DADOS DO PEDIDO");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/search.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Nº Pedido");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/LOGO MENOR.png"))); // NOI18N

        lblusuario.setBackground(new java.awt.Color(51, 255, 102));
        lblusuario.setForeground(new java.awt.Color(0, 204, 51));
        lblusuario.setText("Teste");

        jLabel3.setText("Usuário:");

        TxtFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFiltrarActionPerformed(evt);
            }
        });
        TxtFiltrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtFiltrarKeyPressed(evt);
            }
        });

        jLabel4.setText("Buscar na lista");

        TblDaddosPedidoNovo1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CENTRO DE CUSTO", "Nº OF", "CÓDIGO", "ITEM", "UN", "QTD. PEDIDO", "STATUS", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TblDaddosPedidoNovo1.setRowHeight(20);
        TblDaddosPedidoNovo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblDaddosPedidoNovo1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TblDaddosPedidoNovo1);
        if (TblDaddosPedidoNovo1.getColumnModel().getColumnCount() > 0) {
            TblDaddosPedidoNovo1.getColumnModel().getColumn(0).setMinWidth(25);
            TblDaddosPedidoNovo1.getColumnModel().getColumn(0).setPreferredWidth(25);
            TblDaddosPedidoNovo1.getColumnModel().getColumn(0).setMaxWidth(25);
            TblDaddosPedidoNovo1.getColumnModel().getColumn(1).setMinWidth(150);
            TblDaddosPedidoNovo1.getColumnModel().getColumn(1).setPreferredWidth(150);
            TblDaddosPedidoNovo1.getColumnModel().getColumn(1).setMaxWidth(150);
            TblDaddosPedidoNovo1.getColumnModel().getColumn(2).setMinWidth(80);
            TblDaddosPedidoNovo1.getColumnModel().getColumn(2).setPreferredWidth(80);
            TblDaddosPedidoNovo1.getColumnModel().getColumn(2).setMaxWidth(80);
            TblDaddosPedidoNovo1.getColumnModel().getColumn(3).setMinWidth(80);
            TblDaddosPedidoNovo1.getColumnModel().getColumn(3).setPreferredWidth(80);
            TblDaddosPedidoNovo1.getColumnModel().getColumn(3).setMaxWidth(80);
            TblDaddosPedidoNovo1.getColumnModel().getColumn(4).setPreferredWidth(80);
            TblDaddosPedidoNovo1.getColumnModel().getColumn(5).setPreferredWidth(40);
            TblDaddosPedidoNovo1.getColumnModel().getColumn(5).setMaxWidth(40);
            TblDaddosPedidoNovo1.getColumnModel().getColumn(6).setMinWidth(50);
            TblDaddosPedidoNovo1.getColumnModel().getColumn(6).setPreferredWidth(50);
            TblDaddosPedidoNovo1.getColumnModel().getColumn(6).setMaxWidth(50);
            TblDaddosPedidoNovo1.getColumnModel().getColumn(7).setPreferredWidth(20);
        }

        TxtFiltrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFiltrar1ActionPerformed(evt);
            }
        });
        TxtFiltrar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtFiltrar1KeyPressed(evt);
            }
        });

        jLabel5.setText("Buscar na lista");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TxtNumOfPesqNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(19, 19, 19))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 906, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(287, 287, 287)
                        .addComponent(jLabel1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtFiltrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(TxtNumOfPesqNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2))
                    .addComponent(TxtFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtFiltrar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(lblusuario))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(39, 95, 118));
        jPanel4.setForeground(new java.awt.Color(0, 0, 51));

        jLabel19.setBackground(new java.awt.Color(39, 95, 118));
        jLabel19.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("I - INSERIR DADOS DO PEDIDO - PESQUISAR PEDIDOS PENDENTES DE OF");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 905, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

//String nome = "%" + TxtNumOfPesqNovo.getText() + "%" ;
String nome = TxtNumOfPesqNovo.getText();
//        String nome = TxtNumPedido.getText();
//        String status = CbStatus.getSelectedItem().toString();
        String status = "AGUARDANDO DADOS DO PEDIDO";
        
        DadosPedidosDAO dao = new DadosPedidosDAO();
//        List<DadosPedidos> lista = dao.buscaPedidoPorNumero(nome,status);
        List<DadosPedidos> lista = dao.buscaPedidoPorNumero2(nome,status);
        DefaultTableModel dados = (DefaultTableModel)TblDaddosPedidoNovo.getModel();
        dados.setNumRows(0);
        
        for (DadosPedidos d: lista){
        dados.addRow(new Object[]{
            
            d.getId(),
            d.getCc(),
            d.getPedidoId(),
            d.getCod(),
            d.getItem(),
            d.getUnMedida(),
            d.getQtd(),
            d.getStatus(),
            d.getTipo(),
            
        });
        }
        limparTabela(TblDaddosPedidoNovo1);
        
//        TxtNumOf.setText(TxtNumPedido.getText());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
                String textoDoLabel1 = lblusuario.getText();
         Object[] newFormRows = new Object[10];

         for (int i = 0; i < TblDaddosPedidoNovo1.getRowCount(); i++) {
             newFormRows[0] = TblDaddosPedidoNovo1.getValueAt(i,0);
             newFormRows[1] = TblDaddosPedidoNovo1.getValueAt(i,1);
             newFormRows[2] = TblDaddosPedidoNovo1.getValueAt(i,2);
             newFormRows[3] = TblDaddosPedidoNovo1.getValueAt(i,3);
             newFormRows[4] = TblDaddosPedidoNovo1.getValueAt(i,4);
             newFormRows[5] = TblDaddosPedidoNovo1.getValueAt(i,5);
             newFormRows[7] = TblDaddosPedidoNovo1.getValueAt(i,6);
             newFormRows[8] = TblDaddosPedidoNovo1.getValueAt(i,7);
             newFormRows[9] = TblDaddosPedidoNovo1.getValueAt(i,8);

             FrmDadosPedidosOK.FrmDadosPedidosOKModel.addRow(newFormRows);
         }

         FrmDadosPedidosOK.setUsuario(textoDoLabel1);

         limparTabela(TblDaddosPedidoNovo);
         limparTabela(TblDaddosPedidoNovo1);

         FrmDadosPedidosOK.setVisible(true);

        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowActivated

    private void TxtFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFiltrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFiltrarActionPerformed

    private void TxtFiltrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtFiltrarKeyPressed
         // TODO add your handling code here:
        
        String keyword = TxtFiltrar.getText();
//        searchTable(keyword);
        
        DefaultTableModel model = (DefaultTableModel) TblDaddosPedidoNovo.getModel();
    TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<DefaultTableModel>(model);
    TblDaddosPedidoNovo.setRowSorter(sorter);
    sorter.setRowFilter(RowFilter.regexFilter(keyword));
        
        
        
    }//GEN-LAST:event_TxtFiltrarKeyPressed

    private void TblDaddosPedidoNovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblDaddosPedidoNovoMouseClicked
        // TODO add your handling code here:
        
        int rowIndex = TblDaddosPedidoNovo.getSelectedRow();

        // Obtenha os dados da linha selecionada
        Object[] rowData = new Object[TblDaddosPedidoNovo.getColumnCount()];
        for (int i = 0; i < TblDaddosPedidoNovo.getColumnCount(); i++) {
            rowData[i] = TblDaddosPedidoNovo.getValueAt(rowIndex, i);
        }

        // Adicione a linha à tabela de destino
        DefaultTableModel modelDestino = (DefaultTableModel) TblDaddosPedidoNovo1.getModel();
        modelDestino.addRow(rowData);

        // Remova a linha da tabela de origem
        DefaultTableModel modelOrigem = (DefaultTableModel) TblDaddosPedidoNovo.getModel();
        modelOrigem.removeRow(rowIndex);
    }//GEN-LAST:event_TblDaddosPedidoNovoMouseClicked

    private void TblDaddosPedidoNovo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblDaddosPedidoNovo1MouseClicked
        // TODO add your handling code here:
        
        int rowIndex = TblDaddosPedidoNovo1.getSelectedRow();

        // Obtenha os dados da linha selecionada
        Object[] rowData = new Object[TblDaddosPedidoNovo1.getColumnCount()];
        for (int i = 0; i < TblDaddosPedidoNovo1.getColumnCount(); i++) {
            rowData[i] = TblDaddosPedidoNovo1.getValueAt(rowIndex, i);
        }

        // Adicione a linha à tabela de destino
        DefaultTableModel modelDestino = (DefaultTableModel) TblDaddosPedidoNovo.getModel();
        modelDestino.addRow(rowData);

        // Remova a linha da tabela de origem
        DefaultTableModel modelOrigem = (DefaultTableModel) TblDaddosPedidoNovo1.getModel();
        modelOrigem.removeRow(rowIndex);
        
    }//GEN-LAST:event_TblDaddosPedidoNovo1MouseClicked

    private void TxtFiltrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFiltrar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFiltrar1ActionPerformed

    private void TxtFiltrar1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtFiltrar1KeyPressed
        // TODO add your handling code here:
        
         String keyword = TxtFiltrar1.getText();
//        searchTable(keyword);
        
        DefaultTableModel model = (DefaultTableModel) TblDaddosPedidoNovo1.getModel();
    TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<DefaultTableModel>(model);
    TblDaddosPedidoNovo1.setRowSorter(sorter);
    sorter.setRowFilter(RowFilter.regexFilter(keyword));
    }//GEN-LAST:event_TxtFiltrar1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDadosPedidoNovo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDadosPedidoNovo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDadosPedidoNovo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDadosPedidoNovo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDadosPedidoNovo().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TblDaddosPedidoNovo;
    private javax.swing.JTable TblDaddosPedidoNovo1;
    private javax.swing.JTextField TxtFiltrar;
    private javax.swing.JTextField TxtFiltrar1;
    private javax.swing.JTextField TxtNumOfPesqNovo;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblusuario;
    // End of variables declaration//GEN-END:variables
}
