/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.projeto.view;

import br.programa.dao.DadosPedidosDAO;
import br.programa.model.DadosPedidos;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author samuc
 */
public class FrmEDITARDadosPedidoNovo extends javax.swing.JFrame {
    
    DadosPedidos objpes = new DadosPedidos();
    
    public String usuariologado;
    
    
    public void setTextoDoLabelAnterior(String texto) {
        lblusuario.setText(texto); // substitua "meuLabelNaNovaTela" pelo nome do seu label na FrmInPedidos
    }
    
public void limparTabela(JTable tabela) {
    DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
    modelo.setRowCount(0);
}
    /**
     * Creates new form FrmRecebimentos
     */
    public FrmEDITARDadosPedidoNovo() {
        initComponents();
        
        // Define a imagem da barra superior
        setIconImage(new ImageIcon(getClass().getResource("/imagens/get2.png")).getImage());

        // Define o título
        setTitle("Dados do pedido - Pesquisar");
        
        
    }
            FrmEDITARDadosPedidosOK FrmEDITARDadosPedidosOK = new FrmEDITARDadosPedidosOK();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
//    @SuppressWarnings("unchecked")-
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TblDaddosPedidoNovo1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        TxtNumOfPesqNovo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblusuario = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        TblDaddosPedidoNovo1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CENTRO DE CUSTO", "Nº OF", "CÓDIGO", "ITEM", "UN", "QTD. PEDIDO", "STATUS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TblDaddosPedidoNovo1.setRowHeight(20);
        TblDaddosPedidoNovo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblDaddosPedidoNovo1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TblDaddosPedidoNovo1);
        if (TblDaddosPedidoNovo1.getColumnModel().getColumnCount() > 0) {
            TblDaddosPedidoNovo1.getColumnModel().getColumn(0).setMinWidth(25);
            TblDaddosPedidoNovo1.getColumnModel().getColumn(0).setPreferredWidth(25);
            TblDaddosPedidoNovo1.getColumnModel().getColumn(0).setMaxWidth(25);
            TblDaddosPedidoNovo1.getColumnModel().getColumn(1).setMinWidth(150);
            TblDaddosPedidoNovo1.getColumnModel().getColumn(1).setPreferredWidth(150);
            TblDaddosPedidoNovo1.getColumnModel().getColumn(1).setMaxWidth(150);
            TblDaddosPedidoNovo1.getColumnModel().getColumn(2).setMinWidth(80);
            TblDaddosPedidoNovo1.getColumnModel().getColumn(2).setPreferredWidth(80);
            TblDaddosPedidoNovo1.getColumnModel().getColumn(2).setMaxWidth(80);
            TblDaddosPedidoNovo1.getColumnModel().getColumn(3).setMinWidth(80);
            TblDaddosPedidoNovo1.getColumnModel().getColumn(3).setPreferredWidth(80);
            TblDaddosPedidoNovo1.getColumnModel().getColumn(3).setMaxWidth(80);
            TblDaddosPedidoNovo1.getColumnModel().getColumn(4).setPreferredWidth(80);
            TblDaddosPedidoNovo1.getColumnModel().getColumn(5).setPreferredWidth(40);
            TblDaddosPedidoNovo1.getColumnModel().getColumn(5).setMaxWidth(40);
            TblDaddosPedidoNovo1.getColumnModel().getColumn(6).setMinWidth(50);
            TblDaddosPedidoNovo1.getColumnModel().getColumn(6).setPreferredWidth(50);
            TblDaddosPedidoNovo1.getColumnModel().getColumn(6).setMaxWidth(50);
            TblDaddosPedidoNovo1.getColumnModel().getColumn(7).setPreferredWidth(20);
        }

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/setas-direitas.png"))); // NOI18N
        jButton3.setText("INSERIR DADOS DO PEDIDO");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/search.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        TxtNumOfPesqNovo.setText("AREA PROGRAMATICA 3.1");

        jLabel2.setText("Nº Pedido");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/LOGO MENOR.png"))); // NOI18N

        lblusuario.setBackground(new java.awt.Color(51, 255, 102));
        lblusuario.setForeground(new java.awt.Color(0, 204, 51));
        lblusuario.setText("Teste");

        jLabel3.setText("Usuário:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(287, 287, 287)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(TxtNumOfPesqNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(251, 251, 251)
                                .addComponent(jButton2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 906, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TxtNumOfPesqNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(lblusuario))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(39, 95, 118));
        jPanel4.setForeground(new java.awt.Color(0, 0, 51));

        jLabel19.setBackground(new java.awt.Color(39, 95, 118));
        jLabel19.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("I - INSERIR DADOS DO PEDIDO - PESQUISAR PEDIDOS PENDENTES DE OF");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 905, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

//String nome = "%" + TxtNumOfPesqNovo.getText() + "%" ;
String nome = TxtNumOfPesqNovo.getText();
//        String nome = TxtNumPedido.getText();
//        String status = CbStatus.getSelectedItem().toString();
        String status = "AGUARDANDO RETORNO DO SETOR";
        
        DadosPedidosDAO dao = new DadosPedidosDAO();
        List<DadosPedidos> lista = dao.buscaPedidoPorNumero3(nome,status);
        DefaultTableModel dados = (DefaultTableModel)TblDaddosPedidoNovo1.getModel();
        dados.setNumRows(0);
        
        for (DadosPedidos d: lista){
        dados.addRow(new Object[]{
            
            d.getId(),
            d.getN_nf(),
            d.getNumeroOF(),
            d.getStatus(),
            d.getProjeto(),
            d.getIdForn(),
            d.getFornecedor(),
            d.getCnpjFornecedor(),

            
        });
        }

        
//        TxtNumOf.setText(TxtNumPedido.getText());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
                String textoDoLabel1 = lblusuario.getText();
                
                int[] getSelectedRows = TblDaddosPedidoNovo1.getSelectedRows();
        Object[] newFormRows = new Object[16];

        for (int i = 0; i < getSelectedRows.length; i++) {
            
            newFormRows[0] = TblDaddosPedidoNovo1.getValueAt(getSelectedRows[i],0);
            newFormRows[1] = TblDaddosPedidoNovo1.getValueAt(getSelectedRows[i],1);
            newFormRows[2] = TblDaddosPedidoNovo1.getValueAt(getSelectedRows[i],2);
            newFormRows[3] = TblDaddosPedidoNovo1.getValueAt(getSelectedRows[i],3);
            newFormRows[4] = TblDaddosPedidoNovo1.getValueAt(getSelectedRows[i],4);
            newFormRows[5] = TblDaddosPedidoNovo1.getValueAt(getSelectedRows[i],5);
            newFormRows[6] = TblDaddosPedidoNovo1.getValueAt(getSelectedRows[i],6);
            newFormRows[7] = TblDaddosPedidoNovo1.getValueAt(getSelectedRows[i],7);

            FrmEDITARDadosPedidosOK.TxtIdNota.setText(newFormRows[0].toString());
            FrmEDITARDadosPedidosOK.TxtNumNf.setText(newFormRows[1].toString());
            FrmEDITARDadosPedidosOK.TxtOfAntiga.setText(newFormRows[2].toString());
            FrmEDITARDadosPedidosOK.TxtCentroDeCusto.setText(newFormRows[4].toString());
            FrmEDITARDadosPedidosOK.TxtIdFonecedor.setText(newFormRows[5].toString());
            FrmEDITARDadosPedidosOK.TxtFornecedorDados.setText(newFormRows[6].toString());
            FrmEDITARDadosPedidosOK.TxtCnpj.setText(newFormRows[7].toString());
            
            String valor = newFormRows[2].toString();
            String valorSemUltimosTresDigitos = valor.substring(0, valor.length() - 3);
            FrmEDITARDadosPedidosOK.TxtNumOf3.setText(valorSemUltimosTresDigitos);



//            frmReceberNF.TxtCnpj.setText(newFormRows[2].toString());

//            
            
//            FrmDadosPedidosOK.FrmDadosPedidosOKModel.addRow(newFormRows);
            
         FrmEDITARDadosPedidosOK.setUsuario(textoDoLabel1);

         limparTabela(TblDaddosPedidoNovo1);         

         FrmEDITARDadosPedidosOK.setVisible(true);

        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_formWindowActivated

    private void TblDaddosPedidoNovo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblDaddosPedidoNovo1MouseClicked
        // TODO add your handling code here:
        

    }//GEN-LAST:event_TblDaddosPedidoNovo1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEDITARDadosPedidoNovo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEDITARDadosPedidoNovo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEDITARDadosPedidoNovo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEDITARDadosPedidoNovo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEDITARDadosPedidoNovo().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TblDaddosPedidoNovo1;
    private javax.swing.JTextField TxtNumOfPesqNovo;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblusuario;
    // End of variables declaration//GEN-END:variables
}
