/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.projeto.view;

import br.programa.model.CurrencyRenderer;
import br.programa.dao.DadosPedidosDAO;
import br.programa.dao.InPedidosDAO;
import br.programa.dao.RecebimentosDAO;
import br.programa.model.DadosPedidos;
import br.programa.model.DadosRecebimento;
import br.programa.model.InPedidos;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author samuc
 */
public class FrmEDITARDadosPedidosOK extends javax.swing.JFrame {
    
    public void setUsuario(String usuario) {
        // Faça o que quiser com o texto da label lblusuario na FrmDadosPedidosOk
        // Por exemplo, exiba o texto em um label na FrmDadosPedidosOk
        lblusuario.setText(usuario); // substitua "lblUsuarioNaNovaTela" pelo nome do seu label na FrmDadosPedidosOk
    }
    
    private FrmEditarPesquisarFornecedor FrmEditarPesquisarFornecedor;
    
    CurrencyRenderer currencyRenderer = new CurrencyRenderer();
    
    JTable tblPedidosOk;
    NumberFormat currencyFormat = new DecimalFormat("R$0.00"); // Define o formato de moeda

   DefaultTableModel FrmDadosPedidosOKModel; 
   
       @Override
    public void dispose() {
        super.dispose(); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
        
        DefaultTableModel model = (DefaultTableModel) TblPedidosOk.getModel();
        int rows = model.getRowCount();
        for (int i = rows - 1; i >= 0; i--) {
            model.removeRow(i);
        
    }}


    /**
     * Creates new form FrmDadosPedido
     * 
     */
//    private FrmPesquisarFornecedor FrmPesquisarFornecedor;
    
    public FrmEDITARDadosPedidosOK() {
        initComponents();
        tableHeaders();

               
        this.FrmEditarPesquisarFornecedor = new FrmEditarPesquisarFornecedor();
    }
    
    public void tableHeaders(){
        
        FrmDadosPedidosOKModel =(DefaultTableModel) TblPedidosOk.getModel();

        
    }
    
     public void atualizarTexto(String texto) {
        JOptionPane.showMessageDialog(null,texto);
        TxtFornecedorDados.setText(texto);
        
    }
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        TxtCnpj = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TxtIdNota = new javax.swing.JTextField();
        TxtIdFonecedor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        TxtFornecedorDados = new javax.swing.JTextField();
        CbComprador = new javax.swing.JComboBox<>();
        cbDigOf = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        TxtCentroDeCusto = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TxtDataEnvioOf = new com.toedter.calendar.JDateChooser();
        TxtNumNf = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        TxtOfAntiga = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        TxtNumOf3 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        CbTipo = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblPedidosOk = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblusuario = new javax.swing.JLabel();
        BtnInserir1 = new javax.swing.JButton();
        BtnInserir2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TblPedidosOk1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TblPedidosOk2 = new javax.swing.JTable();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(39, 95, 118));
        jPanel3.setForeground(new java.awt.Color(0, 0, 51));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ll - INSERIR DADOS DO PEDIDOS - ATUALIZAR DADOS DA OF");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TxtCnpj.setEditable(false);
        jPanel2.add(TxtCnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 230, -1));

        jLabel5.setText("FORNECEDOR");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel9.setText("CNPJ");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, -1));

        jLabel6.setText("Modalidade Aquisição");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, -1, -1));

        jLabel10.setText("ID");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 33, -1));

        TxtIdNota.setEditable(false);
        jPanel2.add(TxtIdNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 40, -1));

        TxtIdFonecedor.setEditable(false);
        TxtIdFonecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtIdFonecedorActionPerformed(evt);
            }
        });
        jPanel2.add(TxtIdFonecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 33, -1));

        jLabel2.setText("ID Nota");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/search.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 72, 38, 30));

        jLabel4.setText("Data Envio OF");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, -1));

        TxtFornecedorDados.setEditable(false);
        TxtFornecedorDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFornecedorDadosActionPerformed(evt);
            }
        });
        jPanel2.add(TxtFornecedorDados, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 243, -1));

        CbComprador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não se Aplica - Registro de Preço", "Aliceseilane Lopes", "Samuel Silva", "João Castilho", "Vanessa Moreira", "Gustavo Lemos" }));
        jPanel2.add(CbComprador, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, 177, -1));

        cbDigOf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ".01", ".02", ".03", ".04", ".05", ".06", ".07", ".08", ".09", ".10", ".11", ".12", ".13", ".14", ".15", ".16", ".17", ".18", ".19", ".20", ".21", ".22", ".23", ".24", ".25", ".26", ".27", ".28", ".29", ".30" }));
        cbDigOf.setPreferredSize(new java.awt.Dimension(47, 22));
        cbDigOf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDigOfActionPerformed(evt);
            }
        });
        jPanel2.add(cbDigOf, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, 20));

        jLabel12.setText("Final");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        jLabel13.setText("Comprador");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Compra Direta", "Registro de Preço" }));
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 30, 120, -1));

        TxtCentroDeCusto.setEditable(false);
        TxtCentroDeCusto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCentroDeCustoActionPerformed(evt);
            }
        });
        jPanel2.add(TxtCentroDeCusto, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 90, -1));

        jLabel11.setText("Centro de Custo");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, -1));
        jPanel2.add(TxtDataEnvioOf, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 149, -1));

        TxtNumNf.setEditable(false);
        jPanel2.add(TxtNumNf, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 100, -1));

        jLabel14.setText("Nota Fiscal");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        TxtOfAntiga.setEditable(false);
        jPanel2.add(TxtOfAntiga, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 80, -1));

        jLabel15.setText("OF Antiga");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        jLabel16.setText("OF Nova");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        TxtNumOf3.setEditable(false);
        jPanel2.add(TxtNumOf3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 80, -1));

        jLabel17.setText("Tipo Pedido");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 60, -1, -1));

        CbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MEDICAMENTOS", "MATERIAIS HOSPITALATES", "NUTRIÇÃO", "SANEANTES", "HIGIENIZAÇÃO", "ODONTOLOGIA", "EXPEDIENTE", "EQUIPAMENTOS", "MANUTENÇÃO", "ROUPARIA", "OUTROS" }));
        jPanel2.add(CbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 80, 177, -1));

        TblPedidosOk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CÓDIGO", "ITEM", "PREÇO UNIT", "QTD"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TblPedidosOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblPedidosOkMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TblPedidosOk);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/LOGO MENOR.png"))); // NOI18N

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pencil.png"))); // NOI18N
        jButton2.setText("Editar Dados");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Usuário:");

        lblusuario.setBackground(new java.awt.Color(51, 255, 102));
        lblusuario.setForeground(new java.awt.Color(0, 204, 51));
        lblusuario.setText("Teste");

        BtnInserir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/minus (1).png"))); // NOI18N
        BtnInserir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInserir1ActionPerformed(evt);
            }
        });

        BtnInserir2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/plus (1).png"))); // NOI18N
        BtnInserir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInserir2ActionPerformed(evt);
            }
        });

        TblPedidosOk1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CÓDIGO", "ITEM", "PREÇO UNIT", "QTD"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TblPedidosOk1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblPedidosOk1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TblPedidosOk1);
        if (TblPedidosOk1.getColumnModel().getColumnCount() > 0) {
            TblPedidosOk1.getColumnModel().getColumn(3).setMinWidth(100);
            TblPedidosOk1.getColumnModel().getColumn(3).setPreferredWidth(100);
            TblPedidosOk1.getColumnModel().getColumn(3).setMaxWidth(100);
            TblPedidosOk1.getColumnModel().getColumn(4).setMinWidth(340);
            TblPedidosOk1.getColumnModel().getColumn(4).setPreferredWidth(340);
            TblPedidosOk1.getColumnModel().getColumn(4).setMaxWidth(340);
        }

        TblPedidosOk2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CÓDIGO", "ITEM", "UN", "PREÇO UNIT", "QTD", "PREVISAO", "NOVA PREV"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TblPedidosOk2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblPedidosOk2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TblPedidosOk2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(165, 165, 165)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 404, Short.MAX_VALUE)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 913, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnInserir1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnInserir2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(11, 11, 11)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnInserir1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(BtnInserir2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(149, 149, 149)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(lblusuario))
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
            
        
         float total = 0;
                    for (int i = 0; i < TblPedidosOk2.getRowCount(); i++) {
             TableModel model = TblPedidosOk2.getModel();
             int value1 = Integer.parseInt(model.getValueAt(i, 5).toString());
             int value2 = Integer.parseInt(model.getValueAt(i, 6).toString());
             int sum = value1 + value2;
             if (sum < 0) {
             TblPedidosOk2.setValueAt(0, i, 7); // atribui 0 à coluna 14
             } else {
             TblPedidosOk2.setValueAt(sum, i, 7); // atribui "sum" à coluna 14
             }
                    }
        
        if (TblPedidosOk2.getRowCount() > 0) { //Verificar se a tabela tem pelo menos uma linha
            for (int a = 0; a < TblPedidosOk2.getRowCount(); a++) { //Iterar sobre todas as linhas da tabela
                int valorCol4 = Integer.parseInt(TblPedidosOk2.getValueAt(a, 5).toString()); //Obter o valor da 4ª coluna da linha atual
                int valorCol5 = Integer.parseInt(TblPedidosOk2.getValueAt(a, 6).toString()); //Obter o valor da 5ª coluna da linha atual
                int soma = valorCol4 + valorCol5; //Calcular a soma dos valores
                TblPedidosOk2.setValueAt(soma, a, 7); //Definir o valor da 6ª coluna da linha atual como a soma
            }
            TblPedidosOk2.repaint();
        }
        
        
         Calendar calendar = Calendar.getInstance();
        Date currentDate = calendar.getTime();
        Date selectedDate = TxtDataEnvioOf.getDate();
        
                if (selectedDate.compareTo(currentDate) > 0) {
            JOptionPane.showMessageDialog(null,"Por favor, verificar a data selecionada, pois está em em modo futuro!");
            return;
        } else { 
        
        if(TxtIdFonecedor.getText().isEmpty()){
            
            JOptionPane.showMessageDialog(null, "Por favor, selecionar o fornecedor", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        else{

        DadosPedidos obj3 = new DadosPedidos();
        String value3 = TxtIdNota.getText();
        Object value4 = cbDigOf.getSelectedItem();
        String resultado = value3+value4;
          
        
        DadosPedidosDAO dao2 = new DadosPedidosDAO();
        
         if (dao2.verificarNomeDuplicado(resultado)) {
        // Se o nome já estiver cadastrado, exibe uma mensagem de erro e não cadastra
        JOptionPane.showMessageDialog(null, "Já existe um pedido cadastrado com esse final, por favor verificar número do pedido", "Erro", JOptionPane.ERROR_MESSAGE);
    } else {
         DadosPedidos obj = new DadosPedidos();

            for (int a =0; a <TblPedidosOk.getRowCount();a++){

                    
                Date data = TxtDataEnvioOf.getDate();
                SimpleDateFormat formatador = new SimpleDateFormat("yyyy-MM-dd");
                String dataformatada = formatador.format(data);   
                    
                    
                 obj.setId(Integer.parseInt(TblPedidosOk.getValueAt(a, 0).toString()));               
                 obj.setNumeroOF(TxtNumOf3.getText()+cbDigOf.getSelectedItem());
                 obj.setPedidoId(TxtNumOf3.getText());
                 obj.setData_Envio_OF(dataformatada);
                 obj.setFornecedor(TxtFornecedorDados.getText());
                 obj.setCnpjFornecedor(TxtCnpj.getText());
                 obj.setIdForn(TxtIdFonecedor.getText());
                 obj.setCc(TxtCentroDeCusto.getText());
                 obj.setComprador(CbComprador.getSelectedItem().toString());
                 obj.setP_unit(TblPedidosOk2.getValueAt(a, 4).toString());
                 obj.setCod(TblPedidosOk2.getValueAt(a, 1).toString());
                 obj.setItem(TblPedidosOk2.getValueAt(a,2).toString());
                 obj.setQtd(TblPedidosOk2.getValueAt(a, 5).toString());
                 obj.setUnMedida(TblPedidosOk2.getValueAt(a, 3).toString());
                 obj.setTipo(CbTipo.getSelectedItem().toString());
                 obj.setNumeroProces(TxtNumNf.getText().toString());
                    
                obj.setPrevisão(TblPedidosOk2.getValueAt(a, 7).toString());

                
                 obj.setStatus("AGUARDANDO RECEBIMENTO");
                 
                                
                 DadosPedidosDAO dao = new DadosPedidosDAO();
                 dao.cadastrarOF(obj);
                 dao.excluirEntradasNF(obj);                  
            }
            
             for (int b =0; b <TblPedidosOk2.getRowCount();b++){
                    
                 obj.setId(Integer.parseInt(TblPedidosOk2.getValueAt(b, 0).toString()));  
                 obj.setPrevisão("0");
                 obj.setStatus("OF CANCELADA");
                 
                                 DadosPedidosDAO dao = new DadosPedidosDAO();
                                 dao.editar4(obj);   
                 
             }
            DadosPedidos obj2 = new DadosPedidos();
            obj2.setId(Integer.parseInt(TxtIdNota.getText().toString()));
            obj2.setNumeroOF(TxtNumOf3.getText()+cbDigOf.getSelectedItem());
            obj2.setStatus("AGUARDANDO RECEBIMENTO II");
            
            DadosPedidosDAO dao3 = new DadosPedidosDAO();
            dao3.editar3(obj2);
            

            
            
//            new Utilitarios().LimpaTela(jPanel2);

            this.dispose();
        }
        }

    }//GEN-LAST:event_jButton2ActionPerformed
    }
        public boolean IsSelected(int row, int column, JTable TblPedidos){
         
         return TblPedidos.getValueAt(row, column) !=null;
         
     }
    private void TblPedidosOkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblPedidosOkMouseClicked
        // TODO add your handling code here:  
       
    }//GEN-LAST:event_TblPedidosOkMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
//            this.FrmPesquisarFornecedor.set this.TxtFornecedorDados.setText(String.valueOf(this.FrmPesquisarFornecedor.getForn()));Visible(true);
            this.FrmEditarPesquisarFornecedor.setVisible(true);
            

//           
           
    }//GEN-LAST:event_jButton3ActionPerformed

    private void TxtFornecedorDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFornecedorDadosActionPerformed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_TxtFornecedorDadosActionPerformed

    private void cbDigOfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDigOfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDigOfActionPerformed

    private void TxtIdFonecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIdFonecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtIdFonecedorActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        
//        ////Pesquisar no banco os pedidos.
//
//        String nome = TxtNumNf.getText();
//        String Nof = TxtOfAntiga.getText();
//        
//        RecebimentosDAO dao = new RecebimentosDAO();
//        List<DadosRecebimento> lista = dao.buscaNfPorNumero3(nome,Nof);
//        DefaultTableModel dados = (DefaultTableModel)TblPedidosOk.getModel();
//        dados.setNumRows(0);
//
//        for (DadosRecebimento c: lista){
//        dados.addRow(new Object[]{
//            c.getId(),
//            c.getCod(),
//            c.getItem(),
//            c.getObs1(),
//            c.getPrim_ent_vlunit1(),
//            c.getQtd(),
//            
//
//        });
//        }
//        
//        String NumOf = TxtOfAntiga.getText();
//        String Status = TxtNumNf.getText();
//        
//        RecebimentosDAO dao1 = new RecebimentosDAO();
//        List<DadosRecebimento> lista2 = dao1.buscaNfPorNumero4(NumOf,Status);
//        DefaultTableModel dados1 = (DefaultTableModel)TblPedidosOk2.getModel();
//        dados1.setNumRows(0);
//
//        for (DadosRecebimento c: lista2){
//        dados1.addRow(new Object[]{
//            c.getId(),
//            c.getCod(),
//            c.getItem(),
//            c.getPrim_ent_vlunit1(),
//            c.getPrev(),
//            c.getUltimaentrada(),
//        });
//        }
        
        
                 
    }//GEN-LAST:event_formWindowActivated

    private void TxtCentroDeCustoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCentroDeCustoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCentroDeCustoActionPerformed

    private void BtnInserir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInserir1ActionPerformed
        // TODO add your handling code here:

        // Obtenha o índice da linha selecionada na tabela de origem
        int rowIndex = TblPedidosOk2.getSelectedRow();

        // Obtenha os dados da linha selecionada
        Object[] rowData = new Object[TblPedidosOk2.getColumnCount()];
        for (int i = 0; i < TblPedidosOk2.getColumnCount(); i++) {
            rowData[i] = TblPedidosOk2.getValueAt(rowIndex, i);
        }

        // Adicione a linha à tabela de destino
        DefaultTableModel modelDestino = (DefaultTableModel) TblPedidosOk1.getModel();
        modelDestino.addRow(rowData);

        // Remova a linha da tabela de origem
        DefaultTableModel modelOrigem = (DefaultTableModel) TblPedidosOk2.getModel();
        modelOrigem.removeRow(rowIndex);

    }//GEN-LAST:event_BtnInserir1ActionPerformed

    private void BtnInserir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInserir2ActionPerformed
        // TODO add your handling code here:

        // Obtenha o índice da linha selecionada na tabela de origem
        int rowIndex = TblPedidosOk1.getSelectedRow();

        // Obtenha os dados da linha selecionada
        Object[] rowData = new Object[TblPedidosOk1.getColumnCount()];
        for (int i = 0; i < TblPedidosOk1.getColumnCount(); i++) {
            rowData[i] = TblPedidosOk1.getValueAt(rowIndex, i);
        }

        // Adicione a linha à tabela de destino
        DefaultTableModel modelDestino = (DefaultTableModel) TblPedidosOk2.getModel();
        modelDestino.addRow(rowData);

        // Remova a linha da tabela de origem
        DefaultTableModel modelOrigem = (DefaultTableModel) TblPedidosOk1.getModel();
        modelOrigem.removeRow(rowIndex);

    }//GEN-LAST:event_BtnInserir2ActionPerformed

    private void TblPedidosOk1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblPedidosOk1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TblPedidosOk1MouseClicked

    private void TblPedidosOk2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblPedidosOk2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TblPedidosOk2MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        ////Pesquisar no banco os pedidos.

        String nome = TxtNumNf.getText();
        String Nof = TxtOfAntiga.getText();
        
        RecebimentosDAO dao = new RecebimentosDAO();
        List<DadosRecebimento> lista = dao.buscaNfPorNumero3(nome,Nof);
        DefaultTableModel dados = (DefaultTableModel)TblPedidosOk.getModel();
        dados.setNumRows(0);

        for (DadosRecebimento c: lista){
        dados.addRow(new Object[]{
            c.getId(),
            c.getCod(),
            c.getItem(),
            c.getObs1(),
            c.getPrim_ent_vlunit1(),
            c.getQtd(),
            

        });
        }
        
        String NumOf = TxtOfAntiga.getText();
        String Status = TxtNumNf.getText();
        
        RecebimentosDAO dao1 = new RecebimentosDAO();
        List<DadosRecebimento> lista2 = dao1.buscaNfPorNumero4(NumOf,Status);
        DefaultTableModel dados1 = (DefaultTableModel)TblPedidosOk2.getModel();
        dados1.setNumRows(0);

        for (DadosRecebimento c: lista2){
        dados1.addRow(new Object[]{
            c.getId(),
            c.getCod(),
            c.getItem(),
            c.getUnidade_medida(),
            c.getPrim_ent_vlunit1(),
            c.getPrev(),
            c.getUltimaentrada(),
        });
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEDITARDadosPedidosOK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEDITARDadosPedidosOK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEDITARDadosPedidosOK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEDITARDadosPedidosOK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEDITARDadosPedidosOK().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnInserir1;
    private javax.swing.JButton BtnInserir2;
    private javax.swing.JComboBox<String> CbComprador;
    private javax.swing.JComboBox<String> CbTipo;
    private javax.swing.JTable TblPedidosOk;
    private javax.swing.JTable TblPedidosOk1;
    private javax.swing.JTable TblPedidosOk2;
    public javax.swing.JTextField TxtCentroDeCusto;
    public static javax.swing.JTextField TxtCnpj;
    private com.toedter.calendar.JDateChooser TxtDataEnvioOf;
    public static javax.swing.JTextField TxtFornecedorDados;
    public static javax.swing.JTextField TxtIdFonecedor;
    public javax.swing.JTextField TxtIdNota;
    public javax.swing.JTextField TxtNumNf;
    public javax.swing.JTextField TxtNumOf3;
    public javax.swing.JTextField TxtOfAntiga;
    private javax.swing.JComboBox<String> cbDigOf;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblusuario;
    // End of variables declaration//GEN-END:variables


  
}

