/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.projeto.view;
import com.formdev.flatlaf.FlatDarculaLaf;
import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatLightOwlContrastIJTheme;
import java.awt.BorderLayout;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import static javax.swing.UIManager.setLookAndFeel;
import javax.swing.UnsupportedLookAndFeelException;




/**
 *
 * @author samuc
 */
public class FrmPrincipal extends javax.swing.JFrame {
    
    public String usuariologado;
    public String nivellogado;
    
    private boolean isDarkTheme = false;
  
    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        
        
        initComponents();
        nivellogado = lblper.getText();
        usuariologado = lblusuario.getText();
        
        
        
        // Define a imagem da barra superior
        setIconImage(new ImageIcon(getClass().getResource("/imagens/GET LOGO 256x245.png")).getImage());



        // Define o título
        setTitle("GET - INÍCIO");
        
        
        
    }
    
        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        lblusuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblper = new javax.swing.JLabel();
        escuro = new javax.swing.JLabel();
        Claro = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuValidacao = new javax.swing.JMenu();
        MenuNovoPedido = new javax.swing.JMenuItem();
        MenuDadosPedido = new javax.swing.JMenuItem();
        MenuEditarPedido = new javax.swing.JMenuItem();
        MenuValidacaoEntrega = new javax.swing.JMenuItem();
        MenuRecebimento = new javax.swing.JMenu();
        MenuReceberProdutos = new javax.swing.JMenuItem();
        MenuNotaFiscal = new javax.swing.JMenu();
        MenuAuditoria = new javax.swing.JMenuItem();
        MenuRecebimentoNf = new javax.swing.JMenuItem();
        MenuCadastro = new javax.swing.JMenu();
        MenuFuncionario = new javax.swing.JMenuItem();
        MenuFornecedor = new javax.swing.JMenuItem();
        MenuProdutos = new javax.swing.JMenuItem();
        MenuRelatorio = new javax.swing.JMenu();
        MenuPrevisao = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblusuario.setBackground(new java.awt.Color(51, 255, 102));
        lblusuario.setForeground(new java.awt.Color(0, 204, 51));
        lblusuario.setText("Teste");
        jPanel1.add(lblusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 415, 188, -1));

        jLabel1.setText("Usuário:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 415, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/DO IT LOOGO.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(742, 360, -1, -1));

        lblper.setBackground(new java.awt.Color(51, 255, 102));
        lblper.setForeground(new java.awt.Color(0, 204, 51));
        lblper.setText("Teste");
        jPanel1.add(lblper, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 415, 188, -1));

        escuro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lamp.png"))); // NOI18N
        escuro.setText("Dark Mode");
        escuro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        escuro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                escuroMouseClicked(evt);
            }
        });
        jPanel1.add(escuro, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, 105, 37));

        Claro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bulb (1).png"))); // NOI18N
        Claro.setText("Dark Mode");
        Claro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Claro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClaroMouseClicked(evt);
            }
        });
        jPanel1.add(Claro, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, 105, 34));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        jPanel1.getAccessibleContext().setAccessibleName("");

        MenuValidacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/request.png"))); // NOI18N
        MenuValidacao.setText("Pedidos  ");

        MenuNovoPedido.setText("Novo Pedido");
        MenuNovoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuNovoPedidoActionPerformed(evt);
            }
        });
        MenuValidacao.add(MenuNovoPedido);

        MenuDadosPedido.setText("Dados do Pedido");
        MenuDadosPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuDadosPedidoActionPerformed(evt);
            }
        });
        MenuValidacao.add(MenuDadosPedido);

        MenuEditarPedido.setText("Editar Pedidos");
        MenuEditarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuEditarPedidoActionPerformed(evt);
            }
        });
        MenuValidacao.add(MenuEditarPedido);

        MenuValidacaoEntrega.setText("Validacao Entrega");
        MenuValidacaoEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuValidacaoEntregaActionPerformed(evt);
            }
        });
        MenuValidacao.add(MenuValidacaoEntrega);

        jMenuBar1.add(MenuValidacao);

        MenuRecebimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/entrega.png"))); // NOI18N
        MenuRecebimento.setText("Recebimentos");

        MenuReceberProdutos.setText("Receber produtos");
        MenuReceberProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuReceberProdutosActionPerformed(evt);
            }
        });
        MenuRecebimento.add(MenuReceberProdutos);

        jMenuBar1.add(MenuRecebimento);

        MenuNotaFiscal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/invoice (3).png"))); // NOI18N
        MenuNotaFiscal.setText("Notas Fiscais");

        MenuAuditoria.setText("Auditoria de Notas Fiscais");
        MenuAuditoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAuditoriaActionPerformed(evt);
            }
        });
        MenuNotaFiscal.add(MenuAuditoria);

        MenuRecebimentoNf.setText("Recebimento de Notas Fiscais");
        MenuRecebimentoNf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRecebimentoNfActionPerformed(evt);
            }
        });
        MenuNotaFiscal.add(MenuRecebimentoNf);

        jMenuBar1.add(MenuNotaFiscal);

        MenuCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/candidato.png"))); // NOI18N
        MenuCadastro.setText("Cadastros");

        MenuFuncionario.setText("Funcionários");
        MenuFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuFuncionarioActionPerformed(evt);
            }
        });
        MenuCadastro.add(MenuFuncionario);

        MenuFornecedor.setText("Fornecedores");
        MenuFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuFornecedorActionPerformed(evt);
            }
        });
        MenuCadastro.add(MenuFornecedor);

        MenuProdutos.setText("Produtos");
        MenuProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuProdutosActionPerformed(evt);
            }
        });
        MenuCadastro.add(MenuProdutos);

        jMenuBar1.add(MenuCadastro);

        MenuRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/relatorio-de-negocios.png"))); // NOI18N
        MenuRelatorio.setText("Relatórios");

        MenuPrevisao.setText("Relatório de previsao de entrada");
        MenuPrevisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPrevisaoActionPerformed(evt);
            }
        });
        MenuRelatorio.add(MenuPrevisao);

        jMenuItem1.setText("Visualizar Notas Fiscais");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MenuRelatorio.add(jMenuItem1);

        jMenuBar1.add(MenuRelatorio);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuNovoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuNovoPedidoActionPerformed
        // TODO add your handling code here:
        FrmInPedidos tela = new FrmInPedidos();
        tela.setTextoDoLabelAnterior(usuariologado);
        tela.setVisible(true);

    }//GEN-LAST:event_MenuNovoPedidoActionPerformed

    private void MenuDadosPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuDadosPedidoActionPerformed
        // TODO add your handling code here:
        
        FrmDadosPedidoNovo tela = new FrmDadosPedidoNovo();
        tela.setTextoDoLabelAnterior(usuariologado);
        tela.setVisible(true);

        
    }//GEN-LAST:event_MenuDadosPedidoActionPerformed

    private void MenuEditarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEditarPedidoActionPerformed
        // TODO add your handling code here:
        FrmVisualizarPedidos tela = new FrmVisualizarPedidos();
        tela.setTextoDoLabelAnterior(usuariologado);
        tela.setVisible(true);
    }//GEN-LAST:event_MenuEditarPedidoActionPerformed

    private void MenuReceberProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuReceberProdutosActionPerformed
        // TODO add your handling code here:
        
        FrmRecebimentos tela = new FrmRecebimentos();
        tela.setTextoDoLabelAnterior(usuariologado);
        tela.setVisible(true);
    }//GEN-LAST:event_MenuReceberProdutosActionPerformed

    private void MenuFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuFuncionarioActionPerformed
        // TODO add your handling code here:
        FrmFuncionarios tela = new FrmFuncionarios();
        tela.setTextoDoLabelAnterior(usuariologado);
        tela.setVisible(true);
    }//GEN-LAST:event_MenuFuncionarioActionPerformed

    private void MenuRecebimentoNfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRecebimentoNfActionPerformed
        // TODO add your handling code here:
        
        FrmNotasFiscaisNOVO tela = new FrmNotasFiscaisNOVO();
        tela.setTextoDoLabelAnterior(usuariologado, nivellogado);

        
        tela.setVisible(true);
    }//GEN-LAST:event_MenuRecebimentoNfActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        lblusuario.setText(usuariologado);
        lblper.setText(nivellogado);
        lblper.setVisible(false);
        
    }//GEN-LAST:event_formWindowActivated

    private void MenuPrevisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPrevisaoActionPerformed
        // TODO add your handling code here:
        FrmPrevisaoEntrada tela = new FrmPrevisaoEntrada();
        tela.setTextoDoLabelAnterior(usuariologado);
        tela.setVisible(true);
    }//GEN-LAST:event_MenuPrevisaoActionPerformed

    private void MenuAuditoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAuditoriaActionPerformed
        // TODO add your handling code here:
        
        FrmAuditoriaNf tela = new FrmAuditoriaNf();
        tela.setTextoDoLabelAnterior(usuariologado);
        tela.setVisible(true);
    }//GEN-LAST:event_MenuAuditoriaActionPerformed

    private void MenuFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuFornecedorActionPerformed
        // TODO add your handling code here:
        
        FrmFonecedores tela = new FrmFonecedores();
        tela.setTextoDoLabelAnterior(usuariologado);
        tela.setVisible(true);
    }//GEN-LAST:event_MenuFornecedorActionPerformed

    private void MenuProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuProdutosActionPerformed
        // TODO add your handling code here:
        
        FrmProdutos tela = new FrmProdutos();
        tela.setTextoDoLabelAnterior(usuariologado);
        tela.setVisible(true);
    }//GEN-LAST:event_MenuProdutosActionPerformed

    private void MenuValidacaoEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuValidacaoEntregaActionPerformed
        // TODO add your handling code here:
        
        FrmSaldoRemanescente tela = new FrmSaldoRemanescente();
        tela.setTextoDoLabelAnterior(usuariologado);
        tela.setVisible(true);
        
    }//GEN-LAST:event_MenuValidacaoEntregaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        
        FrmVisualizarNFePedido tela = new FrmVisualizarNFePedido();
        tela.setTextoDoLabelAnterior(usuariologado);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void ClaroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClaroMouseClicked
        // TODO add your handling code here:
    JLabel label = (JLabel) evt.getSource();
        label.setVisible(false);
        escuro.setVisible(true);
         try {
        // aplicando o tema escuro ao formulário
        UIManager.setLookAndFeel(new FlatDarkLaf());
        // atualizando o formulário para refletir as mudanças no tema
        SwingUtilities.updateComponentTreeUI(FrmPrincipal.this);
    } catch (Exception ex) {
        // tratando exceções
        ex.printStackTrace();
    }
         
    }//GEN-LAST:event_ClaroMouseClicked

    private void escuroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_escuroMouseClicked
        // TODO add your handling code here:
        JLabel label = (JLabel) evt.getSource();
         label.setVisible(false);
         Claro.setVisible(true);
         try {
        // aplicando o tema escuro ao formulário
        UIManager.setLookAndFeel(new FlatLightLaf());
        // atualizando o formulário para refletir as mudanças no tema
        SwingUtilities.updateComponentTreeUI(FrmPrincipal.this);
    } catch (Exception ex) {
        // tratando exceções
        ex.printStackTrace();
    }
         
    }//GEN-LAST:event_escuroMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        escuro.setVisible(false);
    }//GEN-LAST:event_formWindowOpened



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception e) {
        }
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Claro;
    public javax.swing.JMenuItem MenuAuditoria;
    private javax.swing.JMenu MenuCadastro;
    public javax.swing.JMenuItem MenuDadosPedido;
    public javax.swing.JMenuItem MenuEditarPedido;
    public javax.swing.JMenuItem MenuFornecedor;
    public javax.swing.JMenuItem MenuFuncionario;
    private javax.swing.JMenu MenuNotaFiscal;
    public javax.swing.JMenuItem MenuNovoPedido;
    public javax.swing.JMenuItem MenuPrevisao;
    public javax.swing.JMenuItem MenuProdutos;
    public javax.swing.JMenuItem MenuReceberProdutos;
    private javax.swing.JMenu MenuRecebimento;
    public javax.swing.JMenuItem MenuRecebimentoNf;
    private javax.swing.JMenu MenuRelatorio;
    private javax.swing.JMenu MenuValidacao;
    private javax.swing.JMenuItem MenuValidacaoEntrega;
    private javax.swing.JLabel escuro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblper;
    private javax.swing.JLabel lblusuario;
    // End of variables declaration//GEN-END:variables


}
