/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.projeto.view;

import br.programa.dao.DadosPedidosDAO;
import br.programa.dao.NotasFiscaisDAO;
import br.programa.dao.ProdutosDAO;
import br.programa.dao.RecebimentosDAO;
import br.programa.model.DadosPedidos;
import br.programa.model.DadosRecebimento;
import br.programa.model.Produtos;
import br.programa.model.Utilitarios;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.math.RoundingMode;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author samuc
 */
public class FrmReceberNF extends javax.swing.JFrame {
    
    public void setUsuario(String usuario) {
        // Faça o que quiser com o texto da label lblusuario na FrmDadosPedidosOk
        // Por exemplo, exiba o texto em um label na FrmDadosPedidosOk
        lblusuario.setText(usuario); // substitua "lblUsuarioNaNovaTela" pelo nome do seu label na FrmDadosPedidosOk
    }
    
    DefaultTableModel FrmReceberNFModel;    

    @Override
    public void dispose() {
        super.dispose(); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
        
        DefaultTableModel model = (DefaultTableModel) TblRecebernFS.getModel();
        int rows = model.getRowCount();
        for (int i = rows - 1; i >= 0; i--) {
            model.removeRow(i);
        
    }}

  
    public void CorNaLinha(){

        String CLASS = "ENTREGA A MAIOR";
        TblRecebernFS.setDefaultRenderer(Object.class,new DefaultTableCellRenderer(){
            @Override
            public Component getTableCellRendererComponent(JTable TblRecebernFS, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                
                JLabel label = (JLabel) super.getTableCellRendererComponent(TblRecebernFS, value, isSelected, hasFocus, row, column); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
            
                Color c = Color.BLACK;
                Object texto = TblRecebernFS.getValueAt(row, 11);
               if(texto != null && CLASS.equals(texto.toString()))
               
                c = Color.RED;
                label.setForeground(c);
                //TblRecebernFS.setSelectionForeground(Color.green);
                
                return label;
            
            }
            
            
        });
    }
    

    /**
     * Creates new form FrmReceberNF
     */
    public FrmReceberNF() {
        initComponents();
        tableHeaders();
    }
    public void tableHeaders(){
        
        FrmReceberNFModel =(DefaultTableModel) TblRecebernFS.getModel();
        
    }

        
    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblRecebernFS = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel17 = new javax.swing.JLabel();
        TxtTotal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblusuario = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        TxtNNf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        TxtProduto = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        TxtCentrodeCust = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        TxtFornecedor = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        TxtPedido = new javax.swing.JTextField();
        TxtOf = new javax.swing.JTextField();
        TxtIdFornecedor = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        TxtDataEmissao = new com.toedter.calendar.JDateChooser();
        TxtDataEntrega = new com.toedter.calendar.JDateChooser();
        TxtDataRecebimentoNf = new com.toedter.calendar.JDateChooser();
        TxtCnpj1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        TxtChecar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(54, 121, 147));
        jPanel4.setForeground(new java.awt.Color(0, 0, 51));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("II - RECEBIMENTO DE ITENS - CADASTRAR ENTREGA");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addContainerGap())
        );

        jPanel3.setForeground(new java.awt.Color(0, 0, 0));

        TblRecebernFS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "forn", "cnpj", "tipo", "centro de custo", "PEDIDO", "Nº OF", "COD SIGMA", "COD VIVA RIO", "ITEM", "UN", "P. UNIT", "QTD SOL", "QTD REC", "P. ENT", "STATUS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TblRecebernFS.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TblRecebernFS);
        if (TblRecebernFS.getColumnModel().getColumnCount() > 0) {
            TblRecebernFS.getColumnModel().getColumn(0).setMinWidth(35);
            TblRecebernFS.getColumnModel().getColumn(0).setPreferredWidth(35);
            TblRecebernFS.getColumnModel().getColumn(0).setMaxWidth(35);
            TblRecebernFS.getColumnModel().getColumn(1).setMinWidth(0);
            TblRecebernFS.getColumnModel().getColumn(1).setPreferredWidth(0);
            TblRecebernFS.getColumnModel().getColumn(1).setMaxWidth(0);
            TblRecebernFS.getColumnModel().getColumn(2).setMinWidth(0);
            TblRecebernFS.getColumnModel().getColumn(2).setPreferredWidth(0);
            TblRecebernFS.getColumnModel().getColumn(2).setMaxWidth(0);
            TblRecebernFS.getColumnModel().getColumn(3).setMinWidth(0);
            TblRecebernFS.getColumnModel().getColumn(3).setPreferredWidth(0);
            TblRecebernFS.getColumnModel().getColumn(3).setMaxWidth(0);
            TblRecebernFS.getColumnModel().getColumn(4).setMinWidth(0);
            TblRecebernFS.getColumnModel().getColumn(4).setPreferredWidth(0);
            TblRecebernFS.getColumnModel().getColumn(4).setMaxWidth(0);
            TblRecebernFS.getColumnModel().getColumn(5).setMinWidth(0);
            TblRecebernFS.getColumnModel().getColumn(5).setPreferredWidth(0);
            TblRecebernFS.getColumnModel().getColumn(5).setMaxWidth(0);
            TblRecebernFS.getColumnModel().getColumn(6).setMinWidth(0);
            TblRecebernFS.getColumnModel().getColumn(6).setPreferredWidth(0);
            TblRecebernFS.getColumnModel().getColumn(6).setMaxWidth(0);
            TblRecebernFS.getColumnModel().getColumn(7).setMinWidth(80);
            TblRecebernFS.getColumnModel().getColumn(7).setPreferredWidth(80);
            TblRecebernFS.getColumnModel().getColumn(7).setMaxWidth(80);
            TblRecebernFS.getColumnModel().getColumn(8).setMinWidth(80);
            TblRecebernFS.getColumnModel().getColumn(8).setPreferredWidth(80);
            TblRecebernFS.getColumnModel().getColumn(8).setMaxWidth(80);
            TblRecebernFS.getColumnModel().getColumn(9).setMinWidth(260);
            TblRecebernFS.getColumnModel().getColumn(9).setPreferredWidth(260);
            TblRecebernFS.getColumnModel().getColumn(9).setMaxWidth(260);
            TblRecebernFS.getColumnModel().getColumn(10).setMinWidth(40);
            TblRecebernFS.getColumnModel().getColumn(10).setPreferredWidth(40);
            TblRecebernFS.getColumnModel().getColumn(10).setMaxWidth(40);
            TblRecebernFS.getColumnModel().getColumn(11).setMinWidth(50);
            TblRecebernFS.getColumnModel().getColumn(11).setPreferredWidth(50);
            TblRecebernFS.getColumnModel().getColumn(11).setMaxWidth(50);
            TblRecebernFS.getColumnModel().getColumn(12).setMinWidth(65);
            TblRecebernFS.getColumnModel().getColumn(12).setPreferredWidth(65);
            TblRecebernFS.getColumnModel().getColumn(12).setMaxWidth(65);
            TblRecebernFS.getColumnModel().getColumn(13).setMinWidth(65);
            TblRecebernFS.getColumnModel().getColumn(13).setPreferredWidth(65);
            TblRecebernFS.getColumnModel().getColumn(13).setMaxWidth(65);
            TblRecebernFS.getColumnModel().getColumn(14).setMinWidth(65);
            TblRecebernFS.getColumnModel().getColumn(14).setPreferredWidth(65);
            TblRecebernFS.getColumnModel().getColumn(14).setMaxWidth(65);
            TblRecebernFS.getColumnModel().getColumn(15).setMinWidth(180);
            TblRecebernFS.getColumnModel().getColumn(15).setPreferredWidth(180);
            TblRecebernFS.getColumnModel().getColumn(15).setMaxWidth(180);
        }

        jScrollPane2.setViewportView(jTextPane1);

        jLabel17.setText("OBS GERAL SOBRE NOTA FISCAL");

        TxtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTotalActionPerformed(evt);
            }
        });

        jLabel11.setText("Valor Nota Fiscal:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/flag.png"))); // NOI18N
        jButton1.setText("REVISAR ");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/checked (1).png"))); // NOI18N
        jButton2.setText("CADASTRAR ");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lblusuario.setBackground(new java.awt.Color(51, 255, 102));
        lblusuario.setForeground(new java.awt.Color(0, 204, 51));
        lblusuario.setText("Teste");

        jLabel4.setText("Usuário:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 918, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(181, 181, 181)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(15, 15, 15)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)
                            .addComponent(jLabel11))
                        .addGap(61, 61, 61)
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblusuario))))
                .addContainerGap())
        );

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TxtNNf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNNfActionPerformed(evt);
            }
        });
        TxtNNf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtNNfKeyPressed(evt);
            }
        });
        jPanel2.add(TxtNNf, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 78, -1));

        jLabel1.setText("Núm NF");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel2.setText("Data Entrega");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, -1));

        jLabel3.setText("Data Emissão");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        jLabel13.setText("Data Recebimento");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, -1, -1));

        TxtProduto.setEditable(false);
        TxtProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtProdutoActionPerformed(evt);
            }
        });
        jPanel2.add(TxtProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 28, 183, -1));

        jLabel15.setText("Tipo de Pedido");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 6, 87, -1));

        TxtCentrodeCust.setEditable(false);
        TxtCentrodeCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCentrodeCustActionPerformed(evt);
            }
        });
        jPanel2.add(TxtCentrodeCust, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 28, 262, -1));

        jLabel14.setText("Projeto");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 6, -1, -1));

        TxtFornecedor.setEditable(false);
        TxtFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFornecedorActionPerformed(evt);
            }
        });
        jPanel2.add(TxtFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 326, -1));

        jLabel12.setText("Fornecedor");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        jLabel21.setText("Número OF:");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 6, -1, -1));

        jLabel20.setText("Número Pedido: ");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        TxtPedido.setEditable(false);
        TxtPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPedidoActionPerformed(evt);
            }
        });
        jPanel2.add(TxtPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 28, 121, -1));

        TxtOf.setEditable(false);
        TxtOf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtOfActionPerformed(evt);
            }
        });
        jPanel2.add(TxtOf, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 28, 170, -1));

        TxtIdFornecedor.setEditable(false);
        TxtIdFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtIdFornecedorActionPerformed(evt);
            }
        });
        jPanel2.add(TxtIdFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 40, -1));

        jLabel16.setText("ID");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));
        jPanel2.add(TxtDataEmissao, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 140, -1));
        jPanel2.add(TxtDataEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 140, -1));
        jPanel2.add(TxtDataRecebimentoNf, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 140, -1));

        TxtCnpj1.setEditable(false);
        TxtCnpj1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCnpj1ActionPerformed(evt);
            }
        });
        jPanel2.add(TxtCnpj1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 226, -1));

        jLabel18.setText("CNPJ");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, -1, -1));
        jPanel2.add(TxtChecar, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 30, 50, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void TxtNNfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNNfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNNfActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        float total = 0;
                    for (int i = 0; i < TblRecebernFS.getRowCount(); i++) {
             TableModel model = TblRecebernFS.getModel();
             int value1 = Integer.parseInt(model.getValueAt(i, 12).toString());
             int value2 = Integer.parseInt(model.getValueAt(i, 13).toString());
             int sum = value1 - value2;
             if (sum < 0) {
             TblRecebernFS.setValueAt(0, i, 14); // atribui 0 à coluna 14
             } else {
             TblRecebernFS.setValueAt(sum, i, 14); // atribui "sum" à coluna 14
             }

            try {
                float value3 = Float.parseFloat(TblRecebernFS.getValueAt(i, 11).toString());
                float value4 = Integer.parseInt(TblRecebernFS.getValueAt(i, 13).toString());
                float result = value3 * value4;
                total += result;

                DecimalFormat df = new DecimalFormat("#.00");
                df.setRoundingMode(RoundingMode.HALF_UP);
                String valorFormatado = "R$ " + df.format(total); // Adiciona "R$" antes do valor formatado
//                String valorFormatado = df.format(total);

                TxtTotal.setText(valorFormatado);
            } catch (NumberFormatException e) {
                // Tratar a exceção caso a conversão falhe
                // Aqui você pode mostrar uma mensagem de erro ou tomar outra ação apropriada
                e.printStackTrace(); // ou qualquer outra ação que você desejar
            }

            System.out.println(i);
            if (sum > 0) {
                TblRecebernFS.setValueAt("ENTREGA PARCIAL", i, 15);
            }

            if (sum == 0) {
                TblRecebernFS.setValueAt("ENTREGA NA TOTALIDADE", i, 15);
            }
            if (sum < 0) {
                TblRecebernFS.setValueAt("ENTREGA A MAIOR", i, 15);
            }




                       }
                CorNaLinha();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        Calendar calendar = Calendar.getInstance();
        Date currentDate = calendar.getTime();
        Date selectedDate = TxtDataEmissao.getDate();
        Date selectedDate2 = TxtDataEntrega.getDate();
        Date selectedDate3 = TxtDataRecebimentoNf.getDate();
        
                if (selectedDate.compareTo(currentDate) > 0) {
            JOptionPane.showMessageDialog(null,"Por favor, verificar a data selecionada, pois está em em modo futuro!");
            return;
                }
                if (selectedDate2.compareTo(currentDate) > 0) {
            JOptionPane.showMessageDialog(null,"Por favor, verificar a data selecionada, pois está em em modo futuro!");
            return;
                }
                if (selectedDate3.compareTo(currentDate) > 0) {
            JOptionPane.showMessageDialog(null,"Por favor, verificar a data selecionada, pois está em em modo futuro!");
            return;
                }
        
        
        String Nof = TxtOf.getText();
        String Nnf = TxtNNf.getText();
        
        NotasFiscaisDAO dao2 = new NotasFiscaisDAO();
        
         if (dao2.verificarNomeDuplicado(Nof,Nnf)) {
        // Se o nome já estiver cadastrado, exibe uma mensagem de erro e não cadastra
        JOptionPane.showMessageDialog(null, "Já existe uma nota fiscal para esse pedido, por favor verificar número do pedido", "Erro", JOptionPane.ERROR_MESSAGE);
   
         } else {  
        
        //METODO PARA PEGAR DATA DE EMISSÃO
            Date dataEmissao = TxtDataEmissao.getDate();
            SimpleDateFormat formatador = new SimpleDateFormat("yyyy-MM-dd");
            String dataformatadaEmissao = formatador.format(dataEmissao);
            
            //METODO PARA PEGAR DATA DE ENTREGA
            Date dataEntrega = TxtDataEntrega.getDate();
            String dataformatadadataEntrega = formatador.format(dataEntrega);
            
            //METODO PARA PEGAR DATA DE RECEBIMENTO
            Date dataRecebimento = TxtDataRecebimentoNf.getDate();
            String dataformatadadataRecebimento = formatador.format(dataRecebimento);
            
        
        for (int i =0; i <TblRecebernFS.getRowCount();i++){
                           
            DadosPedidos objp = new DadosPedidos();
            DadosRecebimento obj = new DadosRecebimento();
            
            
            
            
            obj.setCod((String) TblRecebernFS.getValueAt(i,8));
            obj.setItem((String) TblRecebernFS.getValueAt(i,9));
            obj.setQtd((String) TblRecebernFS.getValueAt(i,13));
            obj.setUnidade_medida(TblRecebernFS.getValueAt(i, 10).toString());
            obj.setNumnf(TxtNNf.getText()); 
            obj.setNumeroOF(TxtOf.getText()); 
            obj.setPrim_ent_dtemissao(dataformatadaEmissao);
//            obj.setPrim_ent_vltotal1(TxtTotal.getText());
            obj.setProjeto(TxtCentrodeCust.getText());
            obj.setFornecedor(TxtFornecedor.getText());            
            obj.setStatus("Nota Fiscal Lançada");
            obj.setPrim_ent_vlunit1(TblRecebernFS.getValueAt(i,11).toString());
            
            
            objp.setPrevisão(TblRecebernFS.getValueAt(i, 14).toString());
            objp.setStatus(TblRecebernFS.getValueAt(i, 15).toString());      
            objp.setUltimaentrada(TblRecebernFS.getValueAt(i, 13).toString()); 
            objp.setId(Integer.parseInt(TblRecebernFS.getValueAt(i, 0).toString()));
            objp.setNumeroProces(TxtNNf.getText());
            
            

            
            RecebimentosDAO dao = new RecebimentosDAO();
            DadosPedidosDAO dao1 = new DadosPedidosDAO();
            
            dao.cadastrarNfs(obj);        
            dao1.editarPrevisao(objp);

               }
        
        NotasFiscaisDAO dao3 = new NotasFiscaisDAO();
        DadosRecebimento list = new DadosRecebimento();
        
               
        list.setNumnf(TxtNNf.getText());
        list.setNumeroOF(TxtOf.getText());            
        list.setStatus("AGUARDANDO AUDITORIA");        
        list.setValor_total(TxtTotal.getText());
        list.setData_rec(dataformatadadataRecebimento);
        list.setData_emissao(dataformatadaEmissao);
        list.setData_entrega(dataformatadadataEntrega);        
        list.setProjeto(TxtCentrodeCust.getText());
        list.setId_forn(TxtIdFornecedor.getText());
        list.setFornecedor(TxtFornecedor.getText());
        list.setCnpj(TxtCnpj1.getText());
        list.setTipo_produto(TxtProduto.getText());
        
        if(jTextPane1 == null){
            list.setObs1(" ");
    
        } else{
            
            list.setObs1(jTextPane1.getText());
        }

        
        
        dao3.cadastrarNotaFiscal(list);
        
        
         }
        
        JOptionPane.showMessageDialog(null, "Recebimento cadastrado com sucesso!");
        new Utilitarios().LimpaTela(jPanel2);
        new Utilitarios().LimpaTela(jPanel3);
            TxtDataEmissao.setDate(null);
            TxtDataEntrega.setDate(null);
            TxtDataRecebimentoNf.setDate(null);
            
            TblRecebernFS.removeAll();
            
            this.dispose();
         
         
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TxtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTotalActionPerformed

    private void TxtFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFornecedorActionPerformed

    private void TxtCentrodeCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCentrodeCustActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCentrodeCustActionPerformed

    private void TxtProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtProdutoActionPerformed

    private void TxtPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPedidoActionPerformed

    
    private void TxtNNfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNNfKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            TxtPedido.setText(TblRecebernFS.getValueAt(0,1).toString());
            TxtOf.setText(TblRecebernFS.getValueAt(0,2).toString());
            
            DadosPedidos obj = new DadosPedidos();            
            DadosPedidosDAO dao = new DadosPedidosDAO();
            obj = dao.consultarDadosPedido(TxtOf.getText());
            TxtFornecedor.setText(obj.getFornecedor());
            TxtCentrodeCust.setText(obj.getCc());
            TxtProduto.setText(obj.getTipo());            
            
            
        }
        
    }//GEN-LAST:event_TxtNNfKeyPressed

    private void TxtOfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtOfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtOfActionPerformed

    private void TxtIdFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIdFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtIdFornecedorActionPerformed

    private void TxtCnpj1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCnpj1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCnpj1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
//        
//             String OF = TxtOf.getText();
//             String NF = TxtNNf.getText();
//             RecebimentosDAO dao = new RecebimentosDAO();
//             List<DadosRecebimento> lista = dao.ChecarOFrepetida(NF, OF);
//             String resultado = "";
//
//             for (DadosRecebimento obj : lista) {
//                 resultado += obj.getItem() + " ";
//             }
//
//             TxtChecar.setText(resultado);

        
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmReceberNF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmReceberNF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmReceberNF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmReceberNF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmReceberNF().setVisible(true);
                
            }
        });
        
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TblRecebernFS;
    public javax.swing.JTextField TxtCentrodeCust;
    private javax.swing.JTextField TxtChecar;
    public javax.swing.JTextField TxtCnpj1;
    private com.toedter.calendar.JDateChooser TxtDataEmissao;
    private com.toedter.calendar.JDateChooser TxtDataEntrega;
    private com.toedter.calendar.JDateChooser TxtDataRecebimentoNf;
    public javax.swing.JTextField TxtFornecedor;
    public javax.swing.JTextField TxtIdFornecedor;
    private javax.swing.JTextField TxtNNf;
    public javax.swing.JTextField TxtOf;
    public javax.swing.JTextField TxtPedido;
    public javax.swing.JTextField TxtProduto;
    private javax.swing.JTextField TxtTotal;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lblusuario;
    // End of variables declaration//GEN-END:variables

}