/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.projeto.view;

import br.programa.dao.DadosPedidosDAO;
import br.programa.model.DadosPedidos;
import java.awt.Color;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author samuc
 */
public class FrmRecebimentos extends javax.swing.JFrame {
    
    DadosPedidos objpes = new DadosPedidos();
    LinhasColoridasRenderer renderer = new LinhasColoridasRenderer(Color.WHITE, Color.LIGHT_GRAY);
    
        public void setTextoDoLabelAnterior(String texto) {
        lblusuario.setText(texto); // substitua "meuLabelNaNovaTela" pelo nome do seu label na FrmInPedidos
    }

    /**
     * Creates new form FrmRecebimentos
     */
        
        public void limparTabela(JTable tabela) {
    DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
    modelo.setRowCount(0);
}
        
    public FrmRecebimentos() {
        initComponents();
         TblPedidosRec.setDefaultRenderer(Object.class, renderer);
    }
            FrmReceberNF frmReceberNF = new FrmReceberNF();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TblPedidosRec = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        TxtNumOfPesq = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblusuario = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TblPedidosRec.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "forn", "cnpj", "tipo", "centro decusto", "ID PEDIDO", "Nº OF", "CÓD SIGMA", "CÓD VIVA RIO", "NOMENCLATURA", "UM", "P. UNIT", "QTD. PEDIDO", "STATUS", "ID FORNECEDOR"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TblPedidosRec);
        if (TblPedidosRec.getColumnModel().getColumnCount() > 0) {
            TblPedidosRec.getColumnModel().getColumn(0).setMinWidth(25);
            TblPedidosRec.getColumnModel().getColumn(0).setPreferredWidth(25);
            TblPedidosRec.getColumnModel().getColumn(0).setMaxWidth(25);
            TblPedidosRec.getColumnModel().getColumn(1).setMinWidth(0);
            TblPedidosRec.getColumnModel().getColumn(1).setPreferredWidth(0);
            TblPedidosRec.getColumnModel().getColumn(1).setMaxWidth(0);
            TblPedidosRec.getColumnModel().getColumn(2).setMinWidth(0);
            TblPedidosRec.getColumnModel().getColumn(2).setPreferredWidth(0);
            TblPedidosRec.getColumnModel().getColumn(2).setMaxWidth(0);
            TblPedidosRec.getColumnModel().getColumn(3).setMinWidth(0);
            TblPedidosRec.getColumnModel().getColumn(3).setPreferredWidth(0);
            TblPedidosRec.getColumnModel().getColumn(3).setMaxWidth(0);
            TblPedidosRec.getColumnModel().getColumn(4).setMinWidth(0);
            TblPedidosRec.getColumnModel().getColumn(4).setPreferredWidth(0);
            TblPedidosRec.getColumnModel().getColumn(4).setMaxWidth(0);
            TblPedidosRec.getColumnModel().getColumn(5).setMinWidth(80);
            TblPedidosRec.getColumnModel().getColumn(5).setPreferredWidth(80);
            TblPedidosRec.getColumnModel().getColumn(5).setMaxWidth(80);
            TblPedidosRec.getColumnModel().getColumn(6).setMinWidth(80);
            TblPedidosRec.getColumnModel().getColumn(6).setPreferredWidth(80);
            TblPedidosRec.getColumnModel().getColumn(6).setMaxWidth(80);
            TblPedidosRec.getColumnModel().getColumn(7).setMinWidth(80);
            TblPedidosRec.getColumnModel().getColumn(7).setPreferredWidth(80);
            TblPedidosRec.getColumnModel().getColumn(7).setMaxWidth(80);
            TblPedidosRec.getColumnModel().getColumn(8).setMinWidth(80);
            TblPedidosRec.getColumnModel().getColumn(8).setPreferredWidth(80);
            TblPedidosRec.getColumnModel().getColumn(8).setMaxWidth(80);
            TblPedidosRec.getColumnModel().getColumn(9).setPreferredWidth(80);
            TblPedidosRec.getColumnModel().getColumn(10).setPreferredWidth(40);
            TblPedidosRec.getColumnModel().getColumn(10).setMaxWidth(40);
            TblPedidosRec.getColumnModel().getColumn(11).setMinWidth(50);
            TblPedidosRec.getColumnModel().getColumn(11).setPreferredWidth(50);
            TblPedidosRec.getColumnModel().getColumn(11).setMaxWidth(50);
            TblPedidosRec.getColumnModel().getColumn(12).setMinWidth(50);
            TblPedidosRec.getColumnModel().getColumn(12).setPreferredWidth(50);
            TblPedidosRec.getColumnModel().getColumn(12).setMaxWidth(50);
            TblPedidosRec.getColumnModel().getColumn(13).setPreferredWidth(20);
            TblPedidosRec.getColumnModel().getColumn(14).setMinWidth(0);
            TblPedidosRec.getColumnModel().getColumn(14).setPreferredWidth(0);
            TblPedidosRec.getColumnModel().getColumn(14).setMaxWidth(0);
        }

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/setas-direitas.png"))); // NOI18N
        jButton3.setText("IR PARA RECEBIMENTO");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/search.png"))); // NOI18N
        jButton2.setText("Pesquisar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Nº OF");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/LOGO MENOR.png"))); // NOI18N

        jLabel3.setText("Usuário:");

        lblusuario.setBackground(new java.awt.Color(51, 255, 102));
        lblusuario.setForeground(new java.awt.Color(0, 204, 51));
        lblusuario.setText("Teste");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TxtNumOfPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 893, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtNumOfPesq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(lblusuario))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(54, 121, 147));
        jPanel4.setForeground(new java.awt.Color(0, 0, 51));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("I - RECEBIMENTO DE ITENS - SELECIONAR OF");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        String nome = TxtNumOfPesq.getText();
        String status = "AGUARDANDO RECEBIMENTO";
        String status2 = "ENTREGA PARCIAL";
        
        DadosPedidosDAO dao = new DadosPedidosDAO();
        List<DadosPedidos> lista = dao.buscaPedidoPorNumeroOF2(nome,status,status2);
        DefaultTableModel dados = (DefaultTableModel) TblPedidosRec.getModel();
        dados.setNumRows(0);

        for (DadosPedidos d : lista) {
            dados.addRow(new Object[]{
                d.getId(),
                d.getFornecedor(),
                d.getCnpjFornecedor(),
                d.getTipo(),
                d.getCc(),
                d.getPedidoId(),
                d.getNumeroOF(),
                d.getCod(),
                d.getCod(),
                d.getItem(),
                d.getUnMedida(),
                d.getP_unit(),
                d.getPrevisão(),
                d.getStatus(),
                d.getIdForn(),
               
                
                
            });
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        String textoDoLabel1 = lblusuario.getText();

        int[] getSelectedRows = TblPedidosRec.getSelectedRows();
        Object[] newFormRows = new Object[17];

        for (int i = 0; i < getSelectedRows.length; i++) {
            
            newFormRows[0] = TblPedidosRec.getValueAt(getSelectedRows[i],0);
            newFormRows[1] = TblPedidosRec.getValueAt(getSelectedRows[i],1);
            newFormRows[2] = TblPedidosRec.getValueAt(getSelectedRows[i],2);
            newFormRows[3] = TblPedidosRec.getValueAt(getSelectedRows[i],3);
            newFormRows[4] = TblPedidosRec.getValueAt(getSelectedRows[i],4);
            newFormRows[5] = TblPedidosRec.getValueAt(getSelectedRows[i],5);
            newFormRows[6] = TblPedidosRec.getValueAt(getSelectedRows[i],6);
            newFormRows[7] = TblPedidosRec.getValueAt(getSelectedRows[i],7);
            newFormRows[8] = TblPedidosRec.getValueAt(getSelectedRows[i],8);
            newFormRows[9] = TblPedidosRec.getValueAt(getSelectedRows[i],9);
            newFormRows[10] = TblPedidosRec.getValueAt(getSelectedRows[i],10);
            newFormRows[11] = TblPedidosRec.getValueAt(getSelectedRows[i],11);
            newFormRows[12] = TblPedidosRec.getValueAt(getSelectedRows[i],12);
            newFormRows[15] = TblPedidosRec.getValueAt(getSelectedRows[i],13);
            newFormRows[16] = TblPedidosRec.getValueAt(getSelectedRows[i],14);

            
            
//            frmReceberNF.TxtPedido.setText(newFormRows[0].toString());
            frmReceberNF.TxtFornecedor.setText(newFormRows[1].toString());
            frmReceberNF.TxtCnpj1.setText(newFormRows[2].toString());
            frmReceberNF.TxtProduto.setText(newFormRows[3].toString());
            frmReceberNF.TxtCentrodeCust.setText(newFormRows[4].toString());
            frmReceberNF.TxtPedido.setText(newFormRows[5].toString());
            frmReceberNF.TxtOf.setText(newFormRows[6].toString());
            frmReceberNF.TxtIdFornecedor.setText(newFormRows[16].toString());
//            frmReceberNF.TxtProduto.setText(newFormRows[12].toString());
//            frmReceberNF.TxtCentrodeCust.setText(newFormRows[13].toString());
//            
            
            frmReceberNF.FrmReceberNFModel.addRow(newFormRows);

        }
        
         frmReceberNF.setUsuario(textoDoLabel1);
         limparTabela(TblPedidosRec);
        frmReceberNF.setVisible(true);
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRecebimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRecebimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRecebimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRecebimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRecebimentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TblPedidosRec;
    private javax.swing.JTextField TxtNumOfPesq;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblusuario;
    // End of variables declaration//GEN-END:variables
}
