/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.projeto.view;

import br.programa.dao.DadosPedidosDAO;
import br.programa.model.DadosPedidos;
import java.awt.Color;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.time.temporal.ChronoUnit;


/**
 *
 * @author samuc
 */
public class FrmSaldoRemanescente extends javax.swing.JFrame {
    
     public void setTextoDoLabelAnterior(String texto) {
        lblusuario.setText(texto); // substitua "meuLabelNaNovaTela" pelo nome do seu label na FrmInPedidos
     }
    
    DadosPedidos objpes = new DadosPedidos();
    LinhasColoridasRenderer renderer = new LinhasColoridasRenderer(Color.WHITE, Color.LIGHT_GRAY);

    /**
     * Creates new form FrmRecebimentos
     */
    public FrmSaldoRemanescente() {
        initComponents();
         TblPedidosRec.setDefaultRenderer(Object.class, renderer);
    }
            FrmValidarEntregaParcial FrmValidarEntregaParcial = new FrmValidarEntregaParcial();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TblPedidosRec = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        TxtNumOfPesq = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        CbStatus2 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblusuario = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TblPedidosRec.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "forn", "cnpj", "tipo", "centro decusto", "ID PEDIDO", "Nº OF", "CÓD SIGMA", "CÓD VIVA RIO", "NOMENCLATURA", "UM", "P. UNIT", "QTD. PEDIDO", "STATUS", "DATA", "DIAS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TblPedidosRec);
        if (TblPedidosRec.getColumnModel().getColumnCount() > 0) {
            TblPedidosRec.getColumnModel().getColumn(0).setMinWidth(25);
            TblPedidosRec.getColumnModel().getColumn(0).setPreferredWidth(25);
            TblPedidosRec.getColumnModel().getColumn(0).setMaxWidth(25);
            TblPedidosRec.getColumnModel().getColumn(1).setMinWidth(0);
            TblPedidosRec.getColumnModel().getColumn(1).setPreferredWidth(0);
            TblPedidosRec.getColumnModel().getColumn(1).setMaxWidth(0);
            TblPedidosRec.getColumnModel().getColumn(2).setMinWidth(0);
            TblPedidosRec.getColumnModel().getColumn(2).setPreferredWidth(0);
            TblPedidosRec.getColumnModel().getColumn(2).setMaxWidth(0);
            TblPedidosRec.getColumnModel().getColumn(3).setMinWidth(0);
            TblPedidosRec.getColumnModel().getColumn(3).setPreferredWidth(0);
            TblPedidosRec.getColumnModel().getColumn(3).setMaxWidth(0);
            TblPedidosRec.getColumnModel().getColumn(4).setMinWidth(0);
            TblPedidosRec.getColumnModel().getColumn(4).setPreferredWidth(0);
            TblPedidosRec.getColumnModel().getColumn(4).setMaxWidth(0);
            TblPedidosRec.getColumnModel().getColumn(5).setMinWidth(80);
            TblPedidosRec.getColumnModel().getColumn(5).setPreferredWidth(80);
            TblPedidosRec.getColumnModel().getColumn(5).setMaxWidth(80);
            TblPedidosRec.getColumnModel().getColumn(6).setMinWidth(80);
            TblPedidosRec.getColumnModel().getColumn(6).setPreferredWidth(80);
            TblPedidosRec.getColumnModel().getColumn(6).setMaxWidth(80);
            TblPedidosRec.getColumnModel().getColumn(7).setMinWidth(80);
            TblPedidosRec.getColumnModel().getColumn(7).setPreferredWidth(80);
            TblPedidosRec.getColumnModel().getColumn(7).setMaxWidth(80);
            TblPedidosRec.getColumnModel().getColumn(8).setMinWidth(80);
            TblPedidosRec.getColumnModel().getColumn(8).setPreferredWidth(80);
            TblPedidosRec.getColumnModel().getColumn(8).setMaxWidth(80);
            TblPedidosRec.getColumnModel().getColumn(9).setPreferredWidth(80);
            TblPedidosRec.getColumnModel().getColumn(10).setPreferredWidth(40);
            TblPedidosRec.getColumnModel().getColumn(10).setMaxWidth(40);
            TblPedidosRec.getColumnModel().getColumn(11).setMinWidth(50);
            TblPedidosRec.getColumnModel().getColumn(11).setPreferredWidth(50);
            TblPedidosRec.getColumnModel().getColumn(11).setMaxWidth(50);
            TblPedidosRec.getColumnModel().getColumn(12).setMinWidth(50);
            TblPedidosRec.getColumnModel().getColumn(12).setPreferredWidth(50);
            TblPedidosRec.getColumnModel().getColumn(12).setMaxWidth(50);
            TblPedidosRec.getColumnModel().getColumn(13).setPreferredWidth(20);
        }

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/setas-direitas.png"))); // NOI18N
        jButton3.setText("DETALHES DO PEDIDO");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/search.png"))); // NOI18N
        jButton2.setText("Pesquisar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Nº OF");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/LOGO MENOR.png"))); // NOI18N

        CbStatus2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AGUARDANDO RECEBIMENTO", "ENTREGA PARCIAL" }));

        jLabel3.setText("FILTRO QNTD DIAS");

        lblusuario.setBackground(new java.awt.Color(51, 255, 102));
        lblusuario.setForeground(new java.awt.Color(0, 204, 51));
        lblusuario.setText("Teste");

        jLabel12.setText("Usuário:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TxtNumOfPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(CbStatus2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(118, 118, 118))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 893, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtNumOfPesq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CbStatus2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(lblusuario))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(28, 170, 158));
        jPanel4.setForeground(new java.awt.Color(0, 0, 51));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("I - VALIDAÇÃO DE ENTREGA PARCIAL - SELECIONAR PEDIDO");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 787, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        String nome = "%" + TxtNumOfPesq.getText() + "%";
        String status = CbStatus2.getSelectedItem().toString();
        
        DadosPedidosDAO dao = new DadosPedidosDAO();
        List<DadosPedidos> lista = dao.buscaPedidoPorNumeroOF(nome,status);
        DefaultTableModel dados = (DefaultTableModel) TblPedidosRec.getModel();
        dados.setNumRows(0);

       for (DadosPedidos d : lista) {
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd"); // Atualize o formato da data de acordo com o formato da String retornada pelo método getDataPedido()
    LocalDate dataAtual = LocalDate.now(); // Obtém a data atual do sistema

    // Verifica se a data do pedido não está nula
    if (d.getDataPedido() != null) {
        LocalDate dataPedido = LocalDate.parse(d.getDataPedido(), formatter); // Converte a String da data do pedido para LocalDate

        // Calcula a diferença em dias entre a data atual e a data do pedido
        long diferencaDias = ChronoUnit.DAYS.between(dataPedido, dataAtual);

        dados.addRow(new Object[]{
            d.getId(),
            d.getFornecedor(),
            d.getCnpjFornecedor(),
            d.getTipo(),
            d.getCc(),
            d.getPedidoId(),
            d.getNumeroOF(),
            d.getCod(),
            d.getCod(),
            d.getItem(),
            d.getUnMedida(),
            d.getP_unit(),
            d.getPrevisão(),
            d.getStatus(),
            d.getDataPedido(),
            diferencaDias // Adiciona a diferença em dias na última coluna da tabela
        });
    } else {
        // Caso a data do pedido esteja nula, você pode definir um valor padrão ou simplesmente não adicionar a linha na tabela
        dados.addRow(new Object[]{
            d.getId(),
            d.getFornecedor(),
            d.getCnpjFornecedor(),
            d.getTipo(),
            d.getCc(),
            d.getPedidoId(),
            d.getNumeroOF(),
            d.getCod(),
            d.getCod(),
            d.getItem(),
            d.getUnMedida(),
            d.getP_unit(),
            d.getPrevisão(),
            d.getStatus(),
            d.getDataPedido(),
            null // ou algum valor padrão para representar a diferença em dias
        });
    }
}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        String textoDoLabel1 = lblusuario.getText();

        int[] getSelectedRows = TblPedidosRec.getSelectedRows();
        Object[] newFormRows = new Object[16];

        for (int i = 0; i < getSelectedRows.length; i++) {
            
            newFormRows[0] = TblPedidosRec.getValueAt(getSelectedRows[i],0);
            newFormRows[1] = TblPedidosRec.getValueAt(getSelectedRows[i],1);
            newFormRows[2] = TblPedidosRec.getValueAt(getSelectedRows[i],2);
            newFormRows[3] = TblPedidosRec.getValueAt(getSelectedRows[i],3);
            newFormRows[4] = TblPedidosRec.getValueAt(getSelectedRows[i],4);
            newFormRows[5] = TblPedidosRec.getValueAt(getSelectedRows[i],5);
            newFormRows[6] = TblPedidosRec.getValueAt(getSelectedRows[i],6);
            newFormRows[7] = TblPedidosRec.getValueAt(getSelectedRows[i],7);
            newFormRows[8] = TblPedidosRec.getValueAt(getSelectedRows[i],8);
            newFormRows[9] = TblPedidosRec.getValueAt(getSelectedRows[i],9);
            newFormRows[10] = TblPedidosRec.getValueAt(getSelectedRows[i],10);
            newFormRows[11] = TblPedidosRec.getValueAt(getSelectedRows[i],11);
            newFormRows[12] = TblPedidosRec.getValueAt(getSelectedRows[i],12);
            newFormRows[15] = TblPedidosRec.getValueAt(getSelectedRows[i],13);

            
            
//            frmReceberNF.TxtPedido.setText(newFormRows[0].toString());
            FrmValidarEntregaParcial.TxtFornecedor.setText(newFormRows[1].toString());
            FrmValidarEntregaParcial.TxtCnpj.setText(newFormRows[2].toString());
            FrmValidarEntregaParcial.TxtProduto.setText(newFormRows[3].toString());
            FrmValidarEntregaParcial.TxtCentrodeCust.setText(newFormRows[4].toString());
            FrmValidarEntregaParcial.TxtPedido.setText(newFormRows[5].toString());
            FrmValidarEntregaParcial.TxtOf.setText(newFormRows[6].toString());
//            frmReceberNF.TxtProduto.setText(newFormRows[12].toString());
//            frmReceberNF.TxtCentrodeCust.setText(newFormRows[13].toString());
//            
            
            FrmValidarEntregaParcial.FrmValidarEntregaParcialModel.addRow(newFormRows);

        }
        
        FrmValidarEntregaParcial.setUsuario(textoDoLabel1);
        
        FrmValidarEntregaParcial.setVisible(true);
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSaldoRemanescente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSaldoRemanescente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSaldoRemanescente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSaldoRemanescente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSaldoRemanescente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbStatus2;
    private javax.swing.JTable TblPedidosRec;
    private javax.swing.JTextField TxtNumOfPesq;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblusuario;
    // End of variables declaration//GEN-END:variables
}
