/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.projeto.view;

import br.programa.dao.InPedidosDAO;
import br.programa.model.InPedidos;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author samuc
 */
public class FrmVisualizarPedidosNOVO extends javax.swing.JFrame {

        public String usuariologado;
    
        public void setTextoDoLabelAnterior(String texto) {
        lblusuario.setText(texto); // substitua "meuLabelNaNovaTela" pelo nome do seu label na FrmInPedidos
    }
        
    /**
     * Creates new form FrmVisualizarPedido
     */
    public FrmVisualizarPedidosNOVO() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        TxtPesquisa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblVisualizarPedidos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblusuario = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Pesquisar pedido");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/search.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        TxtPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPesquisaActionPerformed(evt);
            }
        });

        TblVisualizarPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DATA PEDIDO", "CENTRO DE CUSTO", "USUARIO", "Nº PEDIDO", "Nº OF", "COD", "ITEM", "QTD", "PREVISAO", "FORNECEDOR", "STATUS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TblVisualizarPedidos.setRowHeight(40);
        TblVisualizarPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblVisualizarPedidosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TblVisualizarPedidos);
        if (TblVisualizarPedidos.getColumnModel().getColumnCount() > 0) {
            TblVisualizarPedidos.getColumnModel().getColumn(0).setMinWidth(30);
            TblVisualizarPedidos.getColumnModel().getColumn(0).setPreferredWidth(30);
            TblVisualizarPedidos.getColumnModel().getColumn(0).setMaxWidth(30);
            TblVisualizarPedidos.getColumnModel().getColumn(1).setMinWidth(0);
            TblVisualizarPedidos.getColumnModel().getColumn(1).setPreferredWidth(0);
            TblVisualizarPedidos.getColumnModel().getColumn(1).setMaxWidth(0);
            TblVisualizarPedidos.getColumnModel().getColumn(2).setMinWidth(0);
            TblVisualizarPedidos.getColumnModel().getColumn(2).setPreferredWidth(0);
            TblVisualizarPedidos.getColumnModel().getColumn(2).setMaxWidth(0);
            TblVisualizarPedidos.getColumnModel().getColumn(3).setMinWidth(0);
            TblVisualizarPedidos.getColumnModel().getColumn(3).setPreferredWidth(0);
            TblVisualizarPedidos.getColumnModel().getColumn(3).setMaxWidth(0);
            TblVisualizarPedidos.getColumnModel().getColumn(4).setMinWidth(0);
            TblVisualizarPedidos.getColumnModel().getColumn(4).setPreferredWidth(0);
            TblVisualizarPedidos.getColumnModel().getColumn(4).setMaxWidth(0);
            TblVisualizarPedidos.getColumnModel().getColumn(5).setMinWidth(60);
            TblVisualizarPedidos.getColumnModel().getColumn(5).setPreferredWidth(60);
            TblVisualizarPedidos.getColumnModel().getColumn(5).setMaxWidth(60);
            TblVisualizarPedidos.getColumnModel().getColumn(6).setMinWidth(70);
            TblVisualizarPedidos.getColumnModel().getColumn(6).setPreferredWidth(70);
            TblVisualizarPedidos.getColumnModel().getColumn(6).setMaxWidth(70);
            TblVisualizarPedidos.getColumnModel().getColumn(7).setMinWidth(320);
            TblVisualizarPedidos.getColumnModel().getColumn(7).setPreferredWidth(320);
            TblVisualizarPedidos.getColumnModel().getColumn(7).setMaxWidth(320);
            TblVisualizarPedidos.getColumnModel().getColumn(8).setMinWidth(35);
            TblVisualizarPedidos.getColumnModel().getColumn(8).setPreferredWidth(35);
            TblVisualizarPedidos.getColumnModel().getColumn(8).setMaxWidth(35);
            TblVisualizarPedidos.getColumnModel().getColumn(9).setMinWidth(50);
            TblVisualizarPedidos.getColumnModel().getColumn(9).setPreferredWidth(50);
            TblVisualizarPedidos.getColumnModel().getColumn(9).setMaxWidth(50);
            TblVisualizarPedidos.getColumnModel().getColumn(10).setMinWidth(240);
            TblVisualizarPedidos.getColumnModel().getColumn(10).setPreferredWidth(240);
            TblVisualizarPedidos.getColumnModel().getColumn(10).setMaxWidth(240);
            TblVisualizarPedidos.getColumnModel().getColumn(11).setMinWidth(240);
            TblVisualizarPedidos.getColumnModel().getColumn(11).setPreferredWidth(240);
            TblVisualizarPedidos.getColumnModel().getColumn(11).setMaxWidth(240);
        }

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/LOGO MENOR.png"))); // NOI18N

        jLabel3.setText("Usuário:");

        lblusuario.setBackground(new java.awt.Color(51, 255, 102));
        lblusuario.setForeground(new java.awt.Color(0, 204, 51));
        lblusuario.setText("Teste");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TxtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1034, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(lblusuario)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(39, 95, 118));
        jPanel4.setForeground(new java.awt.Color(0, 0, 51));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("EDITAR PEDIDO NÃO ENTREGUE");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

    String nome = TxtPesquisa.getText();
    String status = "AGUARDANDO DADOS DO PEDIDO";
    
    InPedidosDAO dao = new InPedidosDAO();
    List<InPedidos> lista = dao.buscaPedidoPorNumero2(nome, status);
    DefaultTableModel dados = (DefaultTableModel) TblVisualizarPedidos.getModel();
    dados.setNumRows(0);

    for (InPedidos d : lista) {
        dados.addRow(new Object[]{
            d.getId(),
            d.getData_pedido(),
            d.getCentro_custo(),
            d.getFuncionario(),
            d.getNum_pedido_sica(), 
            d.getNumeroOF(),
            d.getCod(),
            d.getItem(),
            d.getQtd(),
            d.getPrevisao(),
            d.getFornecedor(),
            
            d.getStatus_pedido(),
        });
    }//GEN-LAST:event_jButton1ActionPerformed
    }
    private void TxtPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPesquisaActionPerformed

    private void TblVisualizarPedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblVisualizarPedidosMouseClicked
        // TODO add your handling code here:
        
       String textoDoLabel1 = lblusuario.getText();

DefaultTableModel modelo = (DefaultTableModel) TblVisualizarPedidos.getModel();

int linhaSelecionada = TblVisualizarPedidos.getSelectedRow();
int colunaSelecionada = TblVisualizarPedidos.getColumnModel().getColumnIndex("Nº PEDIDO");
int colunaSelecionada2 = TblVisualizarPedidos.getColumnModel().getColumnIndex("ID");

Object valorSelecionado = modelo.getValueAt(linhaSelecionada, colunaSelecionada);
String textoSelecionado = valorSelecionado.toString();

Object valorSelecionado2 = modelo.getValueAt(linhaSelecionada, colunaSelecionada2);
String textoSelecionado2 = valorSelecionado2.toString();

FrmVisualizarPedidosInteiro novoFormulario = new FrmVisualizarPedidosInteiro();

novoFormulario.TxtPedidoSica.setText(textoSelecionado);
novoFormulario.TxtId.setText(textoSelecionado2);

novoFormulario.setUsuario(textoDoLabel1);

novoFormulario.setVisible(true);

        
    }//GEN-LAST:event_TblVisualizarPedidosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVisualizarPedidosNOVO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVisualizarPedidosNOVO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVisualizarPedidosNOVO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVisualizarPedidosNOVO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVisualizarPedidosNOVO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TblVisualizarPedidos;
    private javax.swing.JTextField TxtPesquisa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblusuario;
    // End of variables declaration//GEN-END:variables
}
