/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.projeto.view;

import br.programa.dao.DadosPedidosDAO;
import br.programa.dao.NotasFiscaisDAO;
import br.programa.dao.RecebimentosDAO;
import br.programa.model.DadosPedidos;
import br.programa.model.DadosRecebimento;
import br.programa.model.Utilitarios;
import java.awt.Color;
import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author samuc
 */
public class FrmValidarEntregaParcial extends javax.swing.JFrame {
    
    public void setUsuario(String usuario) {
        // Faça o que quiser com o texto da label lblusuario na FrmDadosPedidosOk
        // Por exemplo, exiba o texto em um label na FrmDadosPedidosOk
        lblusuario.setText(usuario); // substitua "lblUsuarioNaNovaTela" pelo nome do seu label na FrmDadosPedidosOk
    }
    
    DefaultTableModel FrmValidarEntregaParcialModel;    

    @Override
    public void dispose() {
        super.dispose(); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
        
        DefaultTableModel model = (DefaultTableModel) TblRecebernFS.getModel();
        int rows = model.getRowCount();
        for (int i = rows - 1; i >= 0; i--) {
            model.removeRow(i);
        
    }}

  
    public void CorNaLinha(){

        String CLASS = "ENTREGA A MAIOR";
        TblRecebernFS.setDefaultRenderer(Object.class,new DefaultTableCellRenderer(){
            @Override
            public Component getTableCellRendererComponent(JTable TblRecebernFS, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                
                JLabel label = (JLabel) super.getTableCellRendererComponent(TblRecebernFS, value, isSelected, hasFocus, row, column); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
            
                Color c = Color.BLACK;
                Object texto = TblRecebernFS.getValueAt(row, 11);
               if(texto != null && CLASS.equals(texto.toString()))
               
                c = Color.RED;
                label.setForeground(c);
                //TblRecebernFS.setSelectionForeground(Color.green);
                
                return label;
            
            }
            
            
        });
    }
    

    /**
     * Creates new form FrmReceberNF
     */
    public FrmValidarEntregaParcial() {
        initComponents();
        tableHeaders();
    }
    public void tableHeaders(){
        
        FrmValidarEntregaParcialModel =(DefaultTableModel) TblRecebernFS.getModel();
        
    }

        
    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblRecebernFS = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel17 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        lblusuario = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        TxtProduto = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        TxtCentrodeCust = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        TxtFornecedor = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        TxtPedido = new javax.swing.JTextField();
        TxtOf = new javax.swing.JTextField();
        TxtCnpj = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        TxtDataRecebimentoNf = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(28, 170, 158));
        jPanel4.setForeground(new java.awt.Color(0, 0, 51));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("II - VALIDAÇÃO DE ENTREGA PARCIAL - VALIDAR ENTREGA");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addContainerGap())
        );

        jPanel3.setForeground(new java.awt.Color(0, 0, 0));

        TblRecebernFS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "forn", "cnpj", "tipo", "centro de custo", "PEDIDO", "Nº OF", "COD SIGMA", "COD VIVA RIO", "ITEM", "UN", "P. UNIT", "QTD SOL", "QTD REC", "P. ENT", "STATUS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TblRecebernFS.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TblRecebernFS);
        if (TblRecebernFS.getColumnModel().getColumnCount() > 0) {
            TblRecebernFS.getColumnModel().getColumn(0).setMinWidth(35);
            TblRecebernFS.getColumnModel().getColumn(0).setPreferredWidth(35);
            TblRecebernFS.getColumnModel().getColumn(0).setMaxWidth(35);
            TblRecebernFS.getColumnModel().getColumn(1).setMinWidth(0);
            TblRecebernFS.getColumnModel().getColumn(1).setPreferredWidth(0);
            TblRecebernFS.getColumnModel().getColumn(1).setMaxWidth(0);
            TblRecebernFS.getColumnModel().getColumn(2).setMinWidth(0);
            TblRecebernFS.getColumnModel().getColumn(2).setPreferredWidth(0);
            TblRecebernFS.getColumnModel().getColumn(2).setMaxWidth(0);
            TblRecebernFS.getColumnModel().getColumn(3).setMinWidth(0);
            TblRecebernFS.getColumnModel().getColumn(3).setPreferredWidth(0);
            TblRecebernFS.getColumnModel().getColumn(3).setMaxWidth(0);
            TblRecebernFS.getColumnModel().getColumn(4).setMinWidth(0);
            TblRecebernFS.getColumnModel().getColumn(4).setPreferredWidth(0);
            TblRecebernFS.getColumnModel().getColumn(4).setMaxWidth(0);
            TblRecebernFS.getColumnModel().getColumn(5).setMinWidth(0);
            TblRecebernFS.getColumnModel().getColumn(5).setPreferredWidth(0);
            TblRecebernFS.getColumnModel().getColumn(5).setMaxWidth(0);
            TblRecebernFS.getColumnModel().getColumn(6).setMinWidth(0);
            TblRecebernFS.getColumnModel().getColumn(6).setPreferredWidth(0);
            TblRecebernFS.getColumnModel().getColumn(6).setMaxWidth(0);
            TblRecebernFS.getColumnModel().getColumn(7).setMinWidth(80);
            TblRecebernFS.getColumnModel().getColumn(7).setPreferredWidth(80);
            TblRecebernFS.getColumnModel().getColumn(7).setMaxWidth(80);
            TblRecebernFS.getColumnModel().getColumn(8).setMinWidth(80);
            TblRecebernFS.getColumnModel().getColumn(8).setPreferredWidth(80);
            TblRecebernFS.getColumnModel().getColumn(8).setMaxWidth(80);
            TblRecebernFS.getColumnModel().getColumn(9).setMinWidth(260);
            TblRecebernFS.getColumnModel().getColumn(9).setPreferredWidth(260);
            TblRecebernFS.getColumnModel().getColumn(9).setMaxWidth(260);
            TblRecebernFS.getColumnModel().getColumn(10).setMinWidth(40);
            TblRecebernFS.getColumnModel().getColumn(10).setPreferredWidth(40);
            TblRecebernFS.getColumnModel().getColumn(10).setMaxWidth(40);
            TblRecebernFS.getColumnModel().getColumn(11).setMinWidth(50);
            TblRecebernFS.getColumnModel().getColumn(11).setPreferredWidth(50);
            TblRecebernFS.getColumnModel().getColumn(11).setMaxWidth(50);
            TblRecebernFS.getColumnModel().getColumn(12).setMinWidth(65);
            TblRecebernFS.getColumnModel().getColumn(12).setPreferredWidth(65);
            TblRecebernFS.getColumnModel().getColumn(12).setMaxWidth(65);
            TblRecebernFS.getColumnModel().getColumn(13).setMinWidth(65);
            TblRecebernFS.getColumnModel().getColumn(13).setPreferredWidth(65);
            TblRecebernFS.getColumnModel().getColumn(13).setMaxWidth(65);
            TblRecebernFS.getColumnModel().getColumn(14).setMinWidth(65);
            TblRecebernFS.getColumnModel().getColumn(14).setPreferredWidth(65);
            TblRecebernFS.getColumnModel().getColumn(14).setMaxWidth(65);
            TblRecebernFS.getColumnModel().getColumn(15).setMinWidth(180);
            TblRecebernFS.getColumnModel().getColumn(15).setPreferredWidth(180);
            TblRecebernFS.getColumnModel().getColumn(15).setMaxWidth(180);
        }

        jScrollPane2.setViewportView(jTextPane1);

        jLabel17.setText("OBS GERAL SOBRE VALIDAÇÃO PARCIAL");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/checked (1).png"))); // NOI18N
        jButton2.setText("VALIDAR RECEBIMENTO");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lblusuario.setBackground(new java.awt.Color(51, 255, 102));
        lblusuario.setForeground(new java.awt.Color(0, 204, 51));
        lblusuario.setText("Teste");

        jLabel18.setText("Usuário:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 918, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jLabel17)
                        .addGap(15, 505, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(lblusuario))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel13.setText("Data Validação Parcial");

        TxtProduto.setEditable(false);
        TxtProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtProdutoActionPerformed(evt);
            }
        });

        jLabel15.setText("Tipo de Pedido");

        TxtCentrodeCust.setEditable(false);
        TxtCentrodeCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCentrodeCustActionPerformed(evt);
            }
        });

        jLabel14.setText("Projeto");

        TxtFornecedor.setEditable(false);
        TxtFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFornecedorActionPerformed(evt);
            }
        });

        jLabel12.setText("Fornecedor");

        jLabel21.setText("Número OF:");

        jLabel20.setText("Número Pedido: ");

        TxtPedido.setEditable(false);
        TxtPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPedidoActionPerformed(evt);
            }
        });

        TxtOf.setEditable(false);
        TxtOf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtOfActionPerformed(evt);
            }
        });

        TxtCnpj.setEditable(false);
        TxtCnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCnpjActionPerformed(evt);
            }
        });

        jLabel16.setText("CNPJ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(TxtPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtOf, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(TxtCentrodeCust, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(134, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12)
                            .addComponent(TxtFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(TxtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(TxtDataRecebimentoNf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(210, 210, 210))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(134, 134, 134))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtOf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtCentrodeCust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TxtFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel16))
                                .addGap(30, 30, 30))
                            .addComponent(TxtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtDataRecebimentoNf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        
        String Nof = TxtOf.getText();
        
        NotasFiscaisDAO dao2 = new NotasFiscaisDAO();

        //METODO PARA PEGAR DATA
            SimpleDateFormat formatador = new SimpleDateFormat("yyyy-MM-dd");
            
            //METODO PARA PEGAR DATA DE RECEBIMENTO
            Date dataRecebimento = TxtDataRecebimentoNf.getDate();
            String dataformatadadataRecebimento = formatador.format(dataRecebimento);
            
        
        for (int i =0; i <TblRecebernFS.getRowCount();i++){                           
            DadosPedidos objp = new DadosPedidos();
            DadosRecebimento obj = new DadosRecebimento();      
            
            obj.setCod((String) TblRecebernFS.getValueAt(i,8));
            obj.setItem((String) TblRecebernFS.getValueAt(i,9));
            obj.setQtd((String) TblRecebernFS.getValueAt(i,13));
            obj.setNumeroOF(TxtOf.getText()); 
            obj.setProjeto(TxtCentrodeCust.getText());
            obj.setFornecedor(TxtFornecedor.getText());            
            obj.setStatus("Nota Fiscal Lançada");
            obj.setPrim_ent_vlunit1(TblRecebernFS.getValueAt(i,11).toString());

            
            objp.setPrevisão(TblRecebernFS.getValueAt(i, 14).toString());
            objp.setStatus(TblRecebernFS.getValueAt(i, 15).toString());            
            objp.setId(Integer.parseInt(TblRecebernFS.getValueAt(i, 0).toString()));
            

            
            RecebimentosDAO dao = new RecebimentosDAO();
            DadosPedidosDAO dao1 = new DadosPedidosDAO();
            
            dao.cadastrarNfs(obj);        
            dao1.editarPrevisao(objp);

               }
                
        DadosRecebimento list = new DadosRecebimento();

        list.setNumeroOF(TxtOf.getText());            
        list.setStatus("AGUARDANDO LANÇAMENTO SICA");    
        list.setData_rec(dataformatadadataRecebimento);
        list.setProjeto(TxtCentrodeCust.getText());
        list.setFornecedor(TxtFornecedor.getText());
        
        NotasFiscaisDAO dao3 = new NotasFiscaisDAO();
        dao3.cadastrarNotaFiscal(list);
        
        
        
        JOptionPane.showMessageDialog(null, "Cadastrado");
        new Utilitarios().LimpaTela(jPanel2);
        new Utilitarios().LimpaTela(jPanel3);
        
            TxtDataRecebimentoNf.setDate(null);
        
         
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TxtFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFornecedorActionPerformed

    private void TxtCentrodeCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCentrodeCustActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCentrodeCustActionPerformed

    private void TxtProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtProdutoActionPerformed

    private void TxtPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPedidoActionPerformed

    
    private void TxtOfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtOfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtOfActionPerformed

    private void TxtCnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCnpjActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmValidarEntregaParcial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmValidarEntregaParcial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmValidarEntregaParcial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmValidarEntregaParcial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmValidarEntregaParcial().setVisible(true);
                
            }
        });
        
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TblRecebernFS;
    public javax.swing.JTextField TxtCentrodeCust;
    public javax.swing.JTextField TxtCnpj;
    private com.toedter.calendar.JDateChooser TxtDataRecebimentoNf;
    public javax.swing.JTextField TxtFornecedor;
    public javax.swing.JTextField TxtOf;
    public javax.swing.JTextField TxtPedido;
    public javax.swing.JTextField TxtProduto;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lblusuario;
    // End of variables declaration//GEN-END:variables

}