/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.projeto.view;

import br.programa.dao.DadosPedidosDAO;
import br.programa.dao.ProdutosDAO;
import br.programa.model.DadosPedidos;
import br.programa.model.Produtos;
import br.programa.model.Utilitarios;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import jxl.Workbook;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

        

/**
 *
 * @author samuc
 */
public class FrmVisualizarPedidosInteiro extends javax.swing.JFrame {
    
    public void setUsuario(String usuario) {
        // Faça o que quiser com o texto da label lblusuario na FrmDadosPedidosOk
        // Por exemplo, exiba o texto em um label na FrmDadosPedidosOk
        lblusuario.setText(usuario); // substitua "lblUsuarioNaNovaTela" pelo nome do seu label na FrmDadosPedidosOk
    }

    int qtd;
    int pedido_sica_id;
    File file;
    Workbook Workbook;

    DefaultTableModel carrinho;
     

    /**
     * Creates new form FrmPedidos
     */
    public FrmVisualizarPedidosInteiro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jDayChooser1 = new com.toedter.calendar.JDayChooser();
        jPanel1 = new javax.swing.JPanel();
        cbCentrodeCusto = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        TxtPedidoSica = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ChPedidoUrgente = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        CbTipoProd = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        TxtCodJDE = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtItem = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxtUnMedida = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TxtQuantSica = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        BtnInserir = new javax.swing.JButton();
        TxtGrandeGrupo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jtlocal = new javax.swing.JTextField();
        Txtdatapedido = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaPedidos = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblusuario = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelaPedidos1 = new javax.swing.JTable();
        BtnInserir1 = new javax.swing.JButton();
        BtnInserir2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        TxtId = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        cbCentrodeCusto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AREA PROGRAMATICA 3.1", "AREA PROGRAMATICA 5.2", "AREA PROGRAMATICA 2.2", "HOSPITAL MUNICIPAL PIEDADE", "HOSPITAL MUNICIPAL DR GILSON CANTARINO", "HOSPITAL MUNICIPAL FRANCISCO DA SILVA TELLES", "HOSPITAL MUNICIPAL ALBERT SCHWEITZER" }));
        cbCentrodeCusto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCentrodeCustoActionPerformed(evt);
            }
        });

        jLabel1.setText("ID Pedido Sica");

        TxtPedidoSica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPedidoSicaActionPerformed(evt);
            }
        });
        TxtPedidoSica.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtPedidoSicaKeyPressed(evt);
            }
        });

        jLabel2.setText("Data Pedido");

        ChPedidoUrgente.setText("Emergencial");
        ChPedidoUrgente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChPedidoUrgenteActionPerformed(evt);
            }
        });

        jLabel5.setText("Centro de Custo");

        CbTipoProd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MEDICAMENTOS", "MATERIAIS HOSPITALATES", "NUTRIÇÃO", "SANEANTES", "HIGIENIZAÇÃO", "ODONTOLOGIA", "EXPEDIENTE", "EQUIPAMENTOS", "MANUTENÇÃO", "ROUPARIA", "OUTROS" }));

        jLabel13.setText("Tipo Pedido");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        jLabel12.setText("Observações do Pedido");

        TxtCodJDE.setEditable(false);
        TxtCodJDE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCodJDEActionPerformed(evt);
            }
        });
        TxtCodJDE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtCodJDEKeyPressed(evt);
            }
        });

        jLabel4.setText("Cod. Viva Rio");

        TxtItem.setEditable(false);
        TxtItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtItemActionPerformed(evt);
            }
        });

        jLabel3.setText("Nomenclatura");

        TxtUnMedida.setEditable(false);
        TxtUnMedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUnMedidaActionPerformed(evt);
            }
        });

        jLabel6.setText("UN");

        jLabel7.setText("Qtd");

        BtnInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/checked (1).png"))); // NOI18N
        BtnInserir.setEnabled(false);
        BtnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInserirActionPerformed(evt);
            }
        });

        TxtGrandeGrupo.setEditable(false);
        TxtGrandeGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtGrandeGrupoActionPerformed(evt);
            }
        });
        TxtGrandeGrupo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtGrandeGrupoKeyPressed(evt);
            }
        });

        jLabel8.setText("Grande Grupo");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/attach-file.png"))); // NOI18N
        jButton1.setText("Anexar Pedido");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jtlocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtlocalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jtlocal, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(TxtCodJDE, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(TxtGrandeGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(TxtItem, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtUnMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(TxtQuantSica, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnInserir))
                            .addComponent(jLabel7))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtCodJDE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtUnMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtQuantSica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtGrandeGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtlocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        Txtdatapedido.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(cbCentrodeCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CbTipoProd, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(TxtPedidoSica, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Txtdatapedido, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37)
                                        .addComponent(ChPedidoUrgente)))))
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel13))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbCentrodeCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TxtPedidoSica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CbTipoProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Txtdatapedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ChPedidoUrgente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TabelaPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "G. Grupo", "Cod Viva Rio", "Nomenclatura", "Un", "Quant."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TabelaPedidos);
        if (TabelaPedidos.getColumnModel().getColumnCount() > 0) {
            TabelaPedidos.getColumnModel().getColumn(0).setMinWidth(20);
            TabelaPedidos.getColumnModel().getColumn(0).setPreferredWidth(20);
            TabelaPedidos.getColumnModel().getColumn(0).setMaxWidth(20);
            TabelaPedidos.getColumnModel().getColumn(1).setMinWidth(100);
            TabelaPedidos.getColumnModel().getColumn(1).setPreferredWidth(100);
            TabelaPedidos.getColumnModel().getColumn(1).setMaxWidth(100);
            TabelaPedidos.getColumnModel().getColumn(2).setMinWidth(130);
            TabelaPedidos.getColumnModel().getColumn(2).setPreferredWidth(130);
            TabelaPedidos.getColumnModel().getColumn(2).setMaxWidth(130);
            TabelaPedidos.getColumnModel().getColumn(4).setMinWidth(100);
            TabelaPedidos.getColumnModel().getColumn(4).setPreferredWidth(100);
            TabelaPedidos.getColumnModel().getColumn(4).setMaxWidth(100);
            TabelaPedidos.getColumnModel().getColumn(5).setMinWidth(100);
            TabelaPedidos.getColumnModel().getColumn(5).setPreferredWidth(100);
            TabelaPedidos.getColumnModel().getColumn(5).setMaxWidth(100);
        }

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pencil.png"))); // NOI18N
        jButton2.setText("Editar Pedido");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/LOGO MENOR.png"))); // NOI18N

        jLabel11.setText("Usuário:");

        lblusuario.setBackground(new java.awt.Color(51, 255, 102));
        lblusuario.setForeground(new java.awt.Color(255, 102, 102));
        lblusuario.setText("Teste");

        TabelaPedidos1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "G. Grupo", "Cod Viva Rio", "Nomenclatura", "Un", "Quant."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TabelaPedidos1);
        if (TabelaPedidos1.getColumnModel().getColumnCount() > 0) {
            TabelaPedidos1.getColumnModel().getColumn(0).setMinWidth(20);
            TabelaPedidos1.getColumnModel().getColumn(0).setPreferredWidth(20);
            TabelaPedidos1.getColumnModel().getColumn(0).setMaxWidth(20);
            TabelaPedidos1.getColumnModel().getColumn(1).setMinWidth(100);
            TabelaPedidos1.getColumnModel().getColumn(1).setPreferredWidth(100);
            TabelaPedidos1.getColumnModel().getColumn(1).setMaxWidth(100);
            TabelaPedidos1.getColumnModel().getColumn(2).setMinWidth(130);
            TabelaPedidos1.getColumnModel().getColumn(2).setPreferredWidth(130);
            TabelaPedidos1.getColumnModel().getColumn(2).setMaxWidth(130);
            TabelaPedidos1.getColumnModel().getColumn(4).setMinWidth(100);
            TabelaPedidos1.getColumnModel().getColumn(4).setPreferredWidth(100);
            TabelaPedidos1.getColumnModel().getColumn(4).setMaxWidth(100);
            TabelaPedidos1.getColumnModel().getColumn(5).setMinWidth(100);
            TabelaPedidos1.getColumnModel().getColumn(5).setPreferredWidth(100);
            TabelaPedidos1.getColumnModel().getColumn(5).setMaxWidth(100);
        }

        BtnInserir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/minus (1).png"))); // NOI18N
        BtnInserir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInserir1ActionPerformed(evt);
            }
        });

        BtnInserir2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/plus (1).png"))); // NOI18N
        BtnInserir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInserir2ActionPerformed(evt);
            }
        });

        jLabel14.setText("Tabela para remover itens");

        jLabel15.setText("Tabela de manter itens");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/delete-button.png"))); // NOI18N
        jButton3.setText("Cancelar Pedido");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addGap(103, 103, 103)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 251, Short.MAX_VALUE)
                        .addComponent(jLabel10))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 873, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addComponent(jLabel14)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(TxtId, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnInserir1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnInserir2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(TxtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnInserir1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(lblusuario))
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3))))
                    .addComponent(BtnInserir2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(39, 95, 118));
        jPanel5.setForeground(new java.awt.Color(0, 0, 51));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("EDITAR PEDIDO");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtItemActionPerformed

    private void TxtPedidoSicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPedidoSicaActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_TxtPedidoSicaActionPerformed

    private void TxtCodJDEKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCodJDEKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Produtos obj = new Produtos();
            ProdutosDAO dao = new ProdutosDAO();
            obj = dao.consultarProdutosPorCodigo(TxtCodJDE.getText());
            TxtItem.setText(obj.getItem());
            TxtUnMedida.setText(obj.getUnidade_medida());
            TxtGrandeGrupo.setText(obj.getGrande_grupo());

        }
    }//GEN-LAST:event_TxtCodJDEKeyPressed

    private void BtnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInserirActionPerformed
        // TODO add your handling code here:

        qtd = Integer.parseInt(TxtQuantSica.getText());

        //add itens
        carrinho = (DefaultTableModel) TabelaPedidos.getModel();
        carrinho.addRow(new Object[]{
            TxtGrandeGrupo.getText(),
            TxtCodJDE.getText(),
            TxtItem.getText(),
            TxtUnMedida.getText(),
            TxtQuantSica.getText(),});
         new Utilitarios().LimpaTela(jPanel2);
    }//GEN-LAST:event_BtnInserirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) TabelaPedidos.getModel();
        model.setRowCount(0);
        
        JFileChooser fc = new JFileChooser();
FileNameExtensionFilter filter = new FileNameExtensionFilter("Excel Workbook", "xlsx");
fc.setFileFilter(filter);
fc.setPreferredSize(new Dimension(750, 400));
fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
int resultado = fc.showOpenDialog(this);

if (resultado == JFileChooser.CANCEL_OPTION) {

} else {
    File file = fc.getSelectedFile();
    jtlocal.setText(file.toString().trim());
    try {
        FileInputStream fis = new FileInputStream(file);
        XSSFWorkbook workbook = new XSSFWorkbook(fis);
        XSSFSheet sheet = workbook.getSheetAt(0);
        int linhas = sheet.getPhysicalNumberOfRows();
        // do something with sheet
        
        for (int i = 0; i < linhas; i++) {
    XSSFRow row = sheet.getRow(i);
    XSSFCell codigo = row.getCell(0);

                    Produtos obj = new Produtos();
                    ProdutosDAO dao = new ProdutosDAO();
                    String codigoStr = codigo.toString();
                    obj = dao.consultarProdutosPorCodigo(codigoStr);
                    
                    String teste = obj.getItem();
                    String segunda = "null";


                    if(teste == null){  
                        int linha = i + 1;
                        JOptionPane.showMessageDialog(null, "Código sica incorreto na linha: "+linha);

                        
                    }else{
                            
                    XSSFCell cc = row.getCell(2);
                    String qtdStr = cc.toString();
                    int qtd = Integer.parseInt(qtdStr.substring(0, qtdStr.indexOf('.')));

                DefaultTableModel mp = (DefaultTableModel) TabelaPedidos.getModel();

                mp.addRow(new String[]{
                    obj.getGrande_grupo(),
                    codigo.getStringCellValue(),
                    obj.getItem(),
                    obj.getUnidade_medida(),
                    Integer.toString(qtd)
                    
                });
                    }
}

//            Workbook.close();

        
    
    } catch (IOException ex) {
        Logger.getLogger(FrmVisualizarPedidosInteiro.class.getName()).log(Level.SEVERE, null, ex);
    }
}

        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtlocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtlocalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtlocalActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try {
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        
            int resposta = JOptionPane.showConfirmDialog(null, "Você realmente deseja editar o pedido?", "Confirmação de exclusão", JOptionPane.YES_NO_OPTION);
if (resposta == JOptionPane.YES_OPTION) {
    
    // Se o usuário clicar em "Sim", o código abaixo será executado
    String codigo = TxtPedidoSica.getText();
    DadosPedidos obj = new DadosPedidos();
    DadosPedidosDAO dao1 = new DadosPedidosDAO();
    for (int i =0; i <TabelaPedidos.getRowCount();i++){
        obj.setId(Integer.parseInt(TabelaPedidos.getValueAt(i, 0).toString()));
        obj.setQtd(TabelaPedidos.getValueAt(i, 5).toString());
        obj.setCc(cbCentrodeCusto.getSelectedItem().toString());
        dao1.EditarPedidos(obj);
    }
    
    
    
    String id = TxtId.getText();
    obj.setId(Integer.parseInt(id));
    obj.setCc(cbCentrodeCusto.getSelectedItem().toString());
    dao1.editarPedidos2(obj);
    JOptionPane.showMessageDialog(null, "Pedido editado com sucesso!");
    
    
    new Utilitarios().LimpaTela(jPanel1);
    new Utilitarios().LimpaTela(jPanel2);
    new Utilitarios().LimpaTela(jPanel3);
    dispose();
        
        JOptionPane.showMessageDialog(null,"Por favor, não esqueça editar o pedido no sica");

}

} finally {
        setCursor(Cursor.getDefaultCursor()); // redefine o cursor padrão
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TxtCodJDEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCodJDEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCodJDEActionPerformed

    private void TxtUnMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUnMedidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtUnMedidaActionPerformed

    private void cbCentrodeCustoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCentrodeCustoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCentrodeCustoActionPerformed

    private void ChPedidoUrgenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChPedidoUrgenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChPedidoUrgenteActionPerformed

    private void TxtGrandeGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtGrandeGrupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtGrandeGrupoActionPerformed

    private void TxtGrandeGrupoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtGrandeGrupoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtGrandeGrupoKeyPressed

    private void BtnInserir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInserir1ActionPerformed
        // TODO add your handling code here:
        
        // Obtenha o índice da linha selecionada na tabela de origem
int rowIndex = TabelaPedidos.getSelectedRow();

// Obtenha os dados da linha selecionada
Object[] rowData = new Object[TabelaPedidos.getColumnCount()];
for (int i = 0; i < TabelaPedidos.getColumnCount(); i++) {
    rowData[i] = TabelaPedidos.getValueAt(rowIndex, i);
}

// Adicione a linha à tabela de destino
DefaultTableModel modelDestino = (DefaultTableModel) TabelaPedidos1.getModel();
modelDestino.addRow(rowData);

// Remova a linha da tabela de origem
DefaultTableModel modelOrigem = (DefaultTableModel) TabelaPedidos.getModel();
modelOrigem.removeRow(rowIndex);
        
        
    }//GEN-LAST:event_BtnInserir1ActionPerformed

    private void TxtPedidoSicaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPedidoSicaKeyPressed
        // TODO add your handling code here:
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            
            String nome = "%" + TxtPedidoSica.getText() + "%" ;
        String status = "AGUARDANDO DADOS DO PEDIDO";
        
        DadosPedidosDAO dao = new DadosPedidosDAO();
        List<DadosPedidos> lista = dao.buscaPedidoPorNumero(nome,status);
        DefaultTableModel dados = (DefaultTableModel)TabelaPedidos.getModel();
        dados.setNumRows(0);
        
        for (DadosPedidos d: lista){
        dados.addRow(new Object[]{
            
            d.getId(),
            "",
            d.getCod(),
            d.getItem(),
            d.getUnMedida(),
            d.getQtd(),
            
        });      
        }
        }
        
    }//GEN-LAST:event_TxtPedidoSicaKeyPressed

    private void BtnInserir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInserir2ActionPerformed
        // TODO add your handling code here:
        
         // Obtenha o índice da linha selecionada na tabela de origem
int rowIndex = TabelaPedidos1.getSelectedRow();

// Obtenha os dados da linha selecionada
Object[] rowData = new Object[TabelaPedidos1.getColumnCount()];
for (int i = 0; i < TabelaPedidos1.getColumnCount(); i++) {
    rowData[i] = TabelaPedidos1.getValueAt(rowIndex, i);
}

// Adicione a linha à tabela de destino
DefaultTableModel modelDestino = (DefaultTableModel) TabelaPedidos.getModel();
modelDestino.addRow(rowData);

// Remova a linha da tabela de origem
DefaultTableModel modelOrigem = (DefaultTableModel) TabelaPedidos1.getModel();
modelOrigem.removeRow(rowIndex);
        
    }//GEN-LAST:event_BtnInserir2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        
        int resposta = JOptionPane.showConfirmDialog(null, "Você realmente deseja excluir o pedido?", "Confirmação de exclusão", JOptionPane.YES_NO_OPTION);
if (resposta == JOptionPane.YES_OPTION) {
    
    // Se o usuário clicar em "Sim", o código abaixo será executado
    String codigo = TxtPedidoSica.getText();
    DadosPedidos obj = new DadosPedidos();
    DadosPedidosDAO dao1 = new DadosPedidosDAO();
    for (int i =0; i <TabelaPedidos.getRowCount();i++){
        obj.setId(Integer.parseInt(TabelaPedidos.getValueAt(i, 0).toString()));  
        dao1.excluirPedidos(obj);
    }
    String id = TxtId.getText();
    obj.setId(Integer.parseInt(id));
    dao1.excluirPedidos2(obj);
    JOptionPane.showMessageDialog(null, "Excluído");
    new Utilitarios().LimpaTela(jPanel1);
    new Utilitarios().LimpaTela(jPanel2);
    new Utilitarios().LimpaTela(jPanel3);
    dispose();
}

        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
       
            
        String nome = "%" + TxtPedidoSica.getText() + "%" ;
        String status = "AGUARDANDO DADOS DO PEDIDO";
        
        DadosPedidosDAO dao = new DadosPedidosDAO();
        List<DadosPedidos> lista = dao.buscaPedidoPorNumero(nome,status);
        DefaultTableModel dados = (DefaultTableModel)TabelaPedidos.getModel();
        dados.setNumRows(0);
        
        for (DadosPedidos d: lista){
        dados.addRow(new Object[]{
            
            d.getId(),
            "",
            d.getCod(),
            d.getItem(),
            d.getUnMedida(),
            d.getQtd(),
            
        });      
        }
        
        String codigo = TxtPedidoSica.getText();
        DadosPedidos obj = new DadosPedidos();
        DadosPedidosDAO dao1 = new DadosPedidosDAO();
        obj = (DadosPedidos) dao1.consultarDadosPedido2(codigo);
        CbTipoProd.setSelectedItem(obj.getTipo());
        cbCentrodeCusto.setSelectedItem(obj.getCc());
        Txtdatapedido.setText(obj.getDataPedido());
        
        
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVisualizarPedidosInteiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVisualizarPedidosInteiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVisualizarPedidosInteiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVisualizarPedidosInteiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVisualizarPedidosInteiro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnInserir;
    private javax.swing.JButton BtnInserir1;
    private javax.swing.JButton BtnInserir2;
    private javax.swing.JComboBox<String> CbTipoProd;
    private javax.swing.JCheckBox ChPedidoUrgente;
    private javax.swing.JTable TabelaPedidos;
    private javax.swing.JTable TabelaPedidos1;
    private javax.swing.JTextField TxtCodJDE;
    private javax.swing.JTextField TxtGrandeGrupo;
    public javax.swing.JTextField TxtId;
    private javax.swing.JTextField TxtItem;
    public javax.swing.JTextField TxtPedidoSica;
    private javax.swing.JTextField TxtQuantSica;
    private javax.swing.JTextField TxtUnMedida;
    private javax.swing.JTextField Txtdatapedido;
    private javax.swing.JComboBox<String> cbCentrodeCusto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDayChooser jDayChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField jtlocal;
    private javax.swing.JLabel lblusuario;
    // End of variables declaration//GEN-END:variables
}
